### ISSUE TITLE
Have the builds stopped?

### ISSUE THREAD

**Issue by khao-soi** [lineageos4microg/docker-lineage-cicd#418] opened 2023-05-09 14:00 UTC
It looks like the current image builds stopped after DRG a few days ago: https://download.lineage.microg.org/?sort=time&order=desc

**Comment by D3SOX** [comment] 2023-05-09 16:27
Yup, noticed the same. Wasn't sure where the right place to report this was.

**Comment by khao-soi** [comment] 2023-05-09 16:54
> Yup, noticed the same. Wasn't sure where the right place to report this was.

I'm not sure if this is the right place, either. Let's find out :)

**Comment by Carlos-Rocha** [comment] 2023-05-13 20:24
I wonder if this channel is monitored

**Comment by khao-soi** [comment] 2023-05-16 14:35
> I've offered to make a monetary donation
You can always make donations here: https://liberapay.com/microG/

**Comment by khao-soi** [comment] 2023-05-18 14:49
> I read somewhere that updates are twice a month

With the addition of LOS 20 this has been reduced to once a month, since the build server takes more than 14 days to create all images. More here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/335#issuecomment-1436082195

I guess we have to be a little patient and wait till the next round starts.

**Comment by sp1cyf0x** [comment] 2023-05-19 11:40
> 

I like how if the build process is interrupted, they just ignore all unbuild process and wait for the next cycle. 🫥

**Comment by ivangal2** [comment] 2023-05-19 12:51
I am also volunteering, know some docker too..

**Comment by ivangal2** [comment] 2023-05-29 10:49
So I believe we should wait if there is a next round of builds in the beginning of June. If there is no next round or it ends the same way as the last round, we probably should start thinking what to do with the project. Bananer is probably not active in the project any more (I wrote him email 3 weeks ago, no response). What do you guys think, what are our options?

**Comment by khao-soi** [comment] 2023-05-29 11:24
I've emailed bananer as well. No response yet. Is there anyone else with access to CI/CD pipelines?

**Comment by khao-soi** [comment] 2023-05-29 17:22
@Exodusnick @spolack Maybe you guys can help?

**Comment by bananer** [comment] 2023-05-31 12:18
I've been busy with other parts of my life. Builds should restart tomorrow.

Yeah, I could use some help. Thanks to everybody who volunteered already. There is a lot of trust involved with accessing the build server and I'm not sure how to vet people. Suggestions welcome...

**Comment by khao-soi** [comment] 2023-06-01 07:12
Builds are running.

**Comment by ivangal2** [comment] 2023-06-01 07:14
I was thinking to provide us with the build logs via ELK stack (I can help with setting this up). And make it either public or accessible to a couple of trusted users, so we can investigate problems by ourselves if you are busy. Unfortunately, it does not solve the problem of fixing the actual builds if they got broken, but at least, whoever is interested, can check what is going on. Because like this time, builds got broken, no one responded for 3 weeks and no one knew what was going on, if the project died, etc.

And the problem of fixing the builds may possibly be solved if the build scripts are published to GIT and if they cease to work, we can check the Kibana and anyone can create a pull request to fix it. And admins can just approve/merge it then.

A bit of brain storming...

**Comment by petefoth** [comment] 2023-06-01 08:53
I'd be happy to help checking on build progress and / or debugging failed builds. Also happy to undergo whatever vetting process you think is appropriate :)

**Comment by LuccoJ** [comment] 2023-06-01 21:33
> Builds are running.

If they stop like last time around the letter D, though... I mean, bananer hasn't shown up in a month...

**Comment by levinuss** [comment] 2023-06-01 21:50
> I mean, bananer hasn't shown up in a month...

You have seen https://github.com/lineageos4microg/docker-lineage-cicd/issues/418#issuecomment-1570116855 right? :)

**Comment by StuartJMackintosh** [comment] 2023-06-02 07:12
> I'm not sure how to vet people. Suggestions welcome...

I offer to help with this. Drop me a DM and we can have a chat.

**Comment by jlHertel** [comment] 2023-06-03 15:46
Also happy to provide help. Feel free to DM me and we can chat

**Comment by JQuilty** [comment] 2023-06-04 02:37
Also volunteering to help.

**Comment by ivangal2** [comment] 2023-06-04 11:34
Builds are running fine, we are on letter 'e' now, further than the last time, so far so good.

Great that there are so many volunteers among us. We can start to brainstorm how to utilize the volunteers to help the project become more resilient. Does anyone have an experience with managing volunteers on an open source project?

**Comment by JQuilty** [comment] 2023-06-05 13:54
So, I can confirm at least that the LOS20 builds for `gtaxl4wifi` have been built and flash just fine. I don't know how much further it got, but  up to that point I can confirm it's building properly.

**Comment by D3SOX** [comment] 2023-06-06 07:39
Seems like `guacamole` was skipped. Can someone check why?

**Comment by FintasticMan** [comment] 2023-06-06 10:09
According to the messages in the Matrix server, the build for `guacamole` failed.

**Comment by StuartJMackintosh** [comment] 2023-06-07 12:41
Lemonadep downloaded today and upgrade seems to work so far 👍

Thank you !

**Comment by bstnbuck** [comment] 2023-06-12 11:37
Seems like the current run (only 19.1?) contains failures. On several builds, only the recovery and boot images have been updated. The OS image, on the other hand, has not. 
Please check for 19.1 `gauguin` as soon as possible. 
The last update was on 16.04. (2 months ago!) and I need the update, because the previous one contains errors.

Other examples are `kirin` or `h850`.

**Comment by khao-soi** [comment] 2023-06-12 20:52
I don't think anyone else has gotten access, yet. So its up to @bananer

**Comment by awfm9** [comment] 2023-06-16 10:16
It seems that builds for `sunfish` are quite behind. I really rely on this project to avoid Google services. Any chance to get an updated build? Couldn't really get the past one to work, either. Maybe because of the version mismatch between recovery and image.

**Comment by khao-soi** [comment] 2023-06-16 11:01
> Any chance to get an updated build?

You can always build it yourself. The build process is documented in the readme and the LOS20 specifications can be found in #335.

In general the situation at the moment is not really satisfiying. Some builds fail and we don't get any info for weeks, nor can anyone do anything about it. We really need more maintainers.

**Comment by LuccoJ** [comment] 2023-06-16 18:38
I'm looking at https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net and it doesn't seem like the sunfish build has failed, but rather, it hasn't started at all. Last time it appears is April 14. I don't think it's queued for running, either, as it appears the builds have stopped since there's nothing being built now after "zl1".

**Comment by bstnbuck** [comment] 2023-06-16 19:38
@LuccoJ Did the process for `gauguin` fail or skip?

**Comment by LuccoJ** [comment] 2023-06-16 20:05
@bstnbuck respectfully I am not a Matrix-relaying bot. You can click on the link I gave and easily reach the Matrix room whose history is public and accessible by anyone.

**Comment by bstnbuck** [comment] 2023-06-16 21:19
Pretty much all missing images (19.1, 18.1) seem to be skipped (at least no fail). I support the suggestion for more maintainers.

**Comment by vanMacG** [comment] 2023-06-18 09:04
New image for 18.1 `klte` was built and works fine 👍

**Comment by LuccoJ** [comment] 2023-06-18 18:57
@vanMacG that's correct, and it's Thursday 15th's news: I point this out because if one looked at the builds bot on Matrix like I've indicated, it's clear that it first built LOS 20 images, then LOS 19.1, then LOS 18.

It's absolutely possible that some were skipped entirely, and I think I've seen an example or two (not sure what they were now), but, spoilers! ```Completed build for gauguin```. It definitely didn't just blanket skip all 19.1 and 18.1 images.

**Comment by petefoth** [comment] 2023-06-18 19:40
@LuccoJ wrote
> looking at https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net and it doesn't seem like the sunfish build has failed, but rather, it hasn't started at all.

Comparing the output there for the build runs, we see on Fri, Apr 14 2023
```
Completed build for redfin
Starting build for river
Failed build for river
Starting build for sagit
Completed build for sagit
Starting build for sunfish
Completed build for sunfish
Starting build for surya
Completed build for surya
```

On Fri, Jun 9 2023 we see
```
Starting build for redfin
Completed build for redfin
Starting build for renoir
Completed build for renoir
Starting build for river
Completed build for river
Starting build for sagit
Completed build for sagit
Starting build for sake
Completed build for sake
Starting build for starlte
Completed build for starlte
Starting build for star2lte
Completed build for star2lte
Starting build for surya
Completed build for surya
```
It looks like `renoir`, `sake` and `starlte` were added to the list of devices to build 20.0 for.  Looking in the `https://download.lineage.microg.org/` directory, `renoir` and `sake` previously had 19.1 builds, `starlte` seems to be a new device.

Is it possible that, when the list of devices to build for was modified, `sunfish` was deleted (accidentally or deliberately)?

Time to go hunting for the list of devices to build, and it's commit history

An alternative thought is that the `Failed build for river` on April 14th affected what happened afterwards. I don;t yet know how the builds are performed, or how the list of devices to build for is managed Time to go digging :)

**Comment by FintasticMan** [comment] 2023-06-18 19:55
The list of devices to build is taken from the [LineageOS hudson](https://github.com/LineageOS/hudson) automatically AFAIK, so it's very unlikely that sunfish was excluded.

The builds should be done just with the scripts in this repo, each LineageOS version one after the other.

**Comment by petefoth** [comment] 2023-06-18 20:14
Thanks for that. So I guess we would need to look at the detailed logs from Hudson (or whichever build tool the lineageos4microg uses) to find out why the build for `sunfish` wasn't started in the latest build run. I guess those are not publicly available. 

In this [comment](https://github.com/lineageos4microg/docker-lineage-cicd/issues/166#issuecomment-869768562) to  [an old issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/166) from 2021, we see a list of devices to build for. The final comment from @bananer says:
> I would like to move the scripts to a publicly visible repo in the future.

I guess the relevant repo is not yet publicly visible. If it were, it would allow others to help debug build failures (and support @bananer in other ways)

**Comment by khao-soi** [comment] 2023-06-18 20:31
Making the build logs publically available would be a good start. I don't think there is anything sensitve in it. Let's hope we'll get some response soon.

**Comment by awfm9** [comment] 2023-06-19 12:02
> You can always build it yourself. The build process is documented in the readme and the LOS20 specifications can be found in #335.

Could someone provide complete instructions on how to produce a build that is 1:1 the same as the release I can download, please? It's not obvious from the readme, especially with regards to which add-ons to include and how, where to put the extra manifest files, what parameters to use to fully mirror it.

**Comment by awfm9** [comment] 2023-06-20 15:07
> Not possible. The official builds will be signed with the official LOS signing keys. You don't have access to those keys. You can either generate your own keys, and sign your build with those, or sign the build with test keys, or not sign the build at all. Whichever option you choose, your build will differ from the released builds that you can download .

As I have already expressed in my previous reply, it is not obvious from this README how to include all the add-ons and parameters that are in the downloadable release. Proper step by step instructions with full commands would be much appreciated.

**Comment by giovEra** [comment] 2023-06-20 15:24
> > Not possible. The official builds will be signed with the official LOS signing keys. You don't have access to those keys. You can either generate your own keys, and sign your build with those, or sign the build with test keys, or not sign the build at all. Whichever option you choose, your build will differ from the released builds that you can download .
> 
> As I have already expressed in my previous reply, it is not obvious from this README how to include all the add-ons and parameters that are in the downloadable release. Proper step by step instructions with full commands would be much appreciated.

About "how to include all the add-ons and parameters that are [used]", see [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/241#issuecomment-1003081312).

**Comment by cashflys** [comment] 2023-06-28 21:02
For hotdogb the directory date was updated, but the contents did not change from April.  It appears the build process is dead for this device even though it is still supported on LineageOS proper.  I agree this project isn't dead, but it is not currently being developed.  I think the autopilot is just getting lucky sometimes.  I truly hope this changes but so far not looking good for this particular device.

**Comment by petefoth** [comment] 2023-06-29 09:49
I have had a look at the June build failures. The builds failed for the following devices
1.  deadpool, wade,  m5: these are all TV boxes, and failed with the same error relating to a missing file in the `partner_gms` repo: raised #436
2.  guacomole, guacomoleb, hotdog, hotdogb: all failing with the same error in file `device/oneplus/sm8150-common/sepolicy/private/camera_helper_app.te`
3.  sunfish, Taimen, TP1803, walleye : all failed with missing file errors relating the same file `hardware/google/pixel/lineage_health/device.mk` Interesting 
4.  TP1803 different failure also related to the (new?) health HAL

Re: 3 & 4 - it is interesting a: that they are close together  in the list of build targets, and b:that there was [a change in LOS](https://github.com/LineageOS/android_hardware_lineage_interfaces/commit/1bb72b2cb6d11d038b62b4a9301dfca062c64aba) which introduced the health HAL, and was made ***after*** the build run had started, but before the builds on  sunfish, Taimen, TP1803, walleye started.  So for these devices, 3 & 4 we can wait until the next build run (starting tomorrow) and see if the builds succeed

Re: 2. Again they are close together  in the list of build targets: maybe some changes were made upstream that we hadn't picked when the builds for those devices started. Again, we'll wait and see what happens in tomorrow's build run

Raised #436 to track the TV box failures

Raised #435 to track the others

**Comment by petefoth** [comment] 2023-06-30 06:42
The June build failures are being addressed: see #435 and #436

**Comment by LaPeste** [comment] 2023-07-06 16:04
I can confirm that this time the build for `hotdogb` has successfully completed.
Thank you all for the great work! 🎉🎉

**Comment by mddvul22** [comment] 2023-07-11 12:54
Looks like the July builds crashed after rosemary.  Nothing has been built since yesterday afternoon.

**Comment by petefoth** [comment] 2023-07-11 13:27
The July build failures are tracked in #438 - see my response there

Good news is that many of the June build failures succeeded :)

Unless anyone objects, I plan to close _this_ issue as we are now better at tracking build failures

**Comment by petefoth** [comment] 2023-07-19 07:40
see https://github.com/lineageos4microg/docker-lineage-cicd/issues/361#issuecomment-1641577082

> For number of devices, the May and / or June builds succeeded, but the operation to copy the zips to the download server failed. I have now copied the missing files manually from the build server to the download server for the following devices:
debx gauguin griffin h850 h870 h872 h910 h918 h990 ls997 parker rs988 star2lte starlte us996d us996 us997 vs995

Closing this issue

**Closed by petefoth** 2023-07-19 07:40 UTC
