### ISSUE TITLE
Failing v21 build for lynx with incombatible Kotlin version error

### ISSUE THREAD

**Issue by TheEdgeOfRage** [lineageos4microg/docker-lineage-cicd#587] opened 2024-03-12 11:58 UTC
Since there is no lynx v21 build yet, I've tried to build it myself. The build gets to about 98% and contains this error for several packages:

```
e: /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/d4b309488c825e418f490a272a3c8c5b8ea445ef/./out/.intermediates/prebuilts/sdk/current/androidx/androidx.annotation_annotation/android_common/turbine-combined/androidx.annotation_annotation.jar!/META-INF/kotlin-stdlib.kotlin_module: Module w
as compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/d4b309488c825e418f490a272a3c8c5b8ea445ef/./out/.intermediates/prebuilts/sdk/current/androidx/androidx.annotation_annotation/android_common/turbine-combined/androidx.annotation_annotation.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Mod
ule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/d4b309488c825e418f490a272a3c8c5b8ea445ef/./out/.intermediates/prebuilts/sdk/current/androidx/androidx.annotation_annotation/android_common/turbine-combined/androidx.annotation_annotation.jar!/META-INF/annotation.kotlin_module: Module was
compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/d4b309488c825e418f490a272a3c8c5b8ea445ef/./out/.intermediates/prebuilts/sdk/current/androidx/androidx.annotation_annotation/android_common/turbine-combined/androidx.annotation_annotation.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Mod
ule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

[Link to full log download](https://share.theedgeofrage.com/lineage-21.0-20240312-UNOFFICIAL-lynx.log)

Not sure if this is the thing that causes the build to fail, but I don't see any other obvious errors on the log.

I'm running the build with the following config:

```
docker run \
    -e "BRANCH_NAME=lineage-21.0" \
    -e "DEVICE_LIST=lynx" \
    -e "SIGN_BUILDS=true" \
    -e "KEYS_SUBJECT=/[REDACTED]" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "WITH_GMS=true" \
    -e "OTA_URL=https://[REDACTED]/" \
    -e "USER_NAME=[REDACTED]" \
    -e "USER_MAIL=[REDACTED]" \
    -v "/home/[REDACTED]/dev/android/l4mg/lineage:/srv/src" \
    -v "/home/[REDACTED]/dev/android/l4mg/zips:/srv/zips" \
    -v "/home/[REDACTED]/dev/android/l4mg/logs:/srv/logs" \
    -v "/home/[REDACTED]/dev/android/l4mg/cache:/srv/ccache" \
    -v "/home/[REDACTED]/dev/android/l4mg/keystore:/srv/keys" \
    -v "/home/[REDACTED]/dev/android/l4mg/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```

**Comment by petefoth** [comment] 2024-03-12 12:29
Welcome to the club :) Our 21.0 builds started failing after successfully building devices up to joan. 20.0 and 18.1 builds are also failing, but for different reasons. I suspect this is because changes are happening upstream during our buiid run so we're chasing a moving target.

In our builds we are using `-e "SIGNATURE_SPOOFING=restricted" \` to use the upstream changes to support signature spoofing rather than our patches.  By using `-e "SIGNATURE_SPOOFING=restricted" \` you wil be pulling in ***both*** sets of changes. No reason why that shouldn't work, but it's not been tested.

Sorry I can't be more help with your build, but I'm afraid I have more than enough build failures of my own to deal with :)

Good luck!

**Comment by FintasticMan** [comment] 2024-03-12 13:34
This doesn't look like it's an issue with the sigspoofing patches, rather an issue with the toolchain/tooling. Unfortunately I don't know enough about that to help any further though...

**Comment by TheEdgeOfRage** [comment] 2024-03-12 13:43
Understandable :) I guess I'll wait for official builds then, if they're on the way

**Comment by petefoth** [comment] 2024-04-04 16:51
21.0 builds are completely broken upstream - see [this comment](https://github.com/lineageos4microg/docker-lineage-cicd/issues/592#issuecomment-2022099925)

That may be the cause of this problem, but we wonlt now until that problem is fixed. This issue On Hod until then

**Comment by petefoth** [comment] 2024-04-24 15:21
21.0 builds are working again now, `lynx` has been added back to [the LOS build target list](https://github.com/LineageOS/hudson/blob/main/lineage-build-targets) and new official LOS nightly builds are being made and [published](https://download.lineageos.org/devices/lynx/builds).

We should be making a new los4microg 21.0 build in the May build run and you should be able to uild it yourself if you can't wait 😄 , so I'm going to close this issue now

**Closed by petefoth** 2024-04-24 15:21 UTC
Labels: On Hold, Upstream issue
