### ISSUE TITLE
latest guacamole build broken, please delete

### ISSUE THREAD

**Issue by ristein** [lineageos4microg/docker-lineage-cicd#633] opened 2024-05-25 09:44 UTC
as described here https://github.com/lineageos4microg/docker-lineage-cicd/issues/631 there are issues in the build of guacamole (oneplus 7 pro) from yesterday (20240524).
Would be great if someone could delete that file to save some users from breaking their phone.
Issues I have:
- sim not detected
- no wifi connection
- cant access storage
- settings crashing, not being opened
- "phone and message storage" crashing
- status bar has different battery icon

**Comment by ristein** [comment] 2024-05-25 12:02
Also it would be great to have an update today that fixes this if possible

**Comment by MicahBird** [comment] 2024-05-25 12:31
I agree, I just tested stock lineage and their latest build (lineage-21.0-20240520-nightly-guacamole) and it works as expected!

**Comment by ristein** [comment] 2024-05-25 12:38
@MicahBird  you don't happen to have an idea if it is possible to rescue current install?
Clean install always takes hours for me :disappointed:

**Comment by petefoth** [comment] 2024-05-25 12:46
I've no idea what's caused the problems, and no idea how to fix them. I'll delete the build when I get back to my computer

**Comment by MicahBird** [comment] 2024-05-25 12:48
> @MicahBird you don't happen to have an idea if it is possible to rescue current install? Clean install always takes hours for me 😞

I hear ya... Hmm, until another up to date (functional) build is provided we're kinda stuck... If there was a new update, it would be as simple as Boot into Recovery > Apply Update > Apply from ADB. You could try to [switch your A/B slot](https://xdaforums.com/t/how-to-manually-switch-the-active-slot.4499789/) and hope that one of them has the previous OTA update, but proceed at your own risk. If you absolutely need to recover data, you can always flash TWRP recovery and exfiltrate your data that way!

**Comment by petefoth** [comment] 2024-05-25 14:10
I've removed the latest build, and started a new clean build. If the problems were caused by an unclean build environment, a new build might fix things. I can't test any builds as I don't have access to one of these phones

**Comment by ristein** [comment] 2024-05-25 14:12
thank you a lot. I was just typing to ask you.
Once finished, can I check it via "adb -d sideload ...zip"?
Or do I need to flash other partitions as well?

**Comment by petefoth** [comment] 2024-05-25 14:19
Should be OK to flash it using adb sideload I think, but I don't have any experience with OnePLus phones. If just sideloading the RO .zip file doesn't work, you could try following the LOS installation instruction, flashing additional partitions using fastboot to flash `dtbo.img` and `vbmeta.ing`, (see https://wiki.lineageos.org/devices/guacamole/install/#flashing-additional-partitions), then flashing the recover sing fastboot (see https://wiki.lineageos.org/devices/guacamole/install/#installing-lineage-recovery-using-fastboot)

**Comment by MicahBird** [comment] 2024-05-25 14:24
I can confirm that all you need to do is an adb sideload from recovery! No need to flash the other partitions!

**Comment by ctag** [comment] 2024-05-25 15:23
Warning to other users that don't know what they're doing like me.

Downloaded the [new files](https://download.lineage.microg.org/guacamole/) and checked the sha256sums, though was a little confused that the modified date wasn't today.

I tried booting into recovery and sideloading just the new lineage OS zip, but got `ERROR: recovery: Denying OTA because it's SPL downgrade`.

I then booted to fastboot and flashed the dtbo, vbmeta, and boot images by following the [lineageos guide](https://wiki.lineageos.org/devices/guacamole/install/#flashing-additional-partitions). And then sideloaded the OS zip again. This time the sideload completed, I skipped installing extra packages, and went to reboot to system. The phone came back to recovery with this message:

`Can't load Android system. Your data may be corrupt. If you continue to get this message, you may need to perform a factory data reset and erase all user data stored on this device.`

**Comment by MicahBird** [comment] 2024-05-25 15:27
Ayyyyy, I also came across `ERROR: recovery: Denying OTA because it's SPL downgrade` but it was because I was trying to foolishly downgrade to Lineage OS 20 🤣 

Your probably running into that error because you **_need_** to perform a factory reset from recovery in order to clean up the mess that the (now deleted) May 24th update caused... Hope that helps!

**Comment by ctag** [comment] 2024-05-25 16:09
Thank you @MicahBird! A factory data reset worked. 

Now to contemplate my lack of effort in making backups before this :face_with_head_bandage:

**Comment by petefoth** [comment] 2024-05-25 18:15
OK the new build is available. Please let me know how you get on with it

**Comment by MicahBird** [comment] 2024-05-25 18:33
🎊 🎊  **_Three cheers for @petefoth!_** 🎊 🎊 

I can confirm the latest build is safe **and** fixes the watch issue presented in #631! Thank you so much @petefoth for making all the builds!! 🙇 _I could only dream of building Android from source..._

**Comment by petefoth** [comment] 2024-05-25 18:37
OK. Still no idea what was wrong with the previous build, and sorry for the inconvenience it caused.

@ristein @ctag If you have a chance, please can you try the latest build? I wont close this issue yet, until I'm sure the build works for ore than one user ;)

**Comment by ristein** [comment] 2024-05-25 18:49
working here too.
Thanks a lot!

others please remember to also flash magisk or other mods after rom

**Comment by petefoth** [comment] 2024-05-25 18:53
OK it works for two people - that will do :)
Closing

**Closed by petefoth** 2024-05-25 18:53 UTC
