### ISSUE TITLE
Issues building for Mata

### ISSUE THREAD

**Issue by NadavCE** [lineageos4microg/docker-lineage-cicd#6] opened 2018-03-13 18:56 UTC
I tried building for Mata (Essential PH-1), running the following:

```
docker run \
    -e "BRANCH_NAME=lineage-15.1" \
    -e "DEVICE_LIST=mata" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    -v "/home/user/keys:/srv/keys" \
    -v "/home/user/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd

```

I get the following output:

```
Set cache size limit to 50.0 GB
>> [Tue Mar 13 17:18:06 UTC 2018] Branch:  lineage-15.1
>> [Tue Mar 13 17:18:06 UTC 2018] Devices: mata
>> [Tue Mar 13 17:18:06 UTC 2018] (Re)initializing branch repository
>> [Tue Mar 13 17:18:16 UTC 2018] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Tue Mar 13 17:18:16 UTC 2018] Syncing branch repository
sed: can't read build/core/version_defaults.mk: No such file or directory
sed: can't read build/core/version_defaults.mk: No such file or directory
/root/build.sh: line 142: [: : integer expression expected
>> [Tue Mar 13 17:39:12 UTC 2018] Missing "vendor/cm", aborting

```

The ```~/lineage/LINEAGE_15_1/.repo/projects/build/``` folder is empty apart from kati.git.

It would seem there's an issue with syncing (probably config on my end). I'd be very grateful if anyone has an idea of what could be wrong.

**Comment by corna** [comment] 2018-03-13 19:10
I'll try to reproduce this.

Can you delete the source dir and try again?

**Comment by NadavCE** [comment] 2018-03-13 19:13
Sure. If it's any help, here are my manifests (renamed to .txt for git):
[custom_packages.xml.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/1808310/custom_packages.xml.txt)
[mata.xml.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/1808311/mata.xml.txt)

**Comment by NadavCE** [comment] 2018-03-13 21:26
@corna No dice, still complains about vendor/cm.

**Comment by corna** [comment] 2018-03-13 21:29
Content of `~/lineage/LINEAGE_15_1/`?

**Comment by NadavCE** [comment] 2018-03-13 21:45
Only contains .repo - and .repo contains:

```
manifest.xml

local_manifests:
custom_packages.xml  mata.xml

manifests:
default.xml  README.mkdn  snippets

manifests.git:
branches  description  HEAD   info  objects      refs      svn
config    FETCH_HEAD   hooks  logs  packed-refs  rr-cache

project-objects:
device  invisiblek  LineageOS  platform  TheMuppets

projects:
build   external    hardware  lineage   pdk.git    system  vendor
device  frameworks  kernel    packages  prebuilts  test

repo:
color.py        git_command.pyc  manifest_xml.pyc  repoc
color.pyc       git_config.py    pager.py          subcmds
command.py      git_config.pyc   pager.pyc         SUBMITTING_PATCHES.md
command.pyc     gitc_utils.py    progress.py       tests
COPYING         gitc_utils.pyc   progress.pyc      trace.py
docs            git_refs.py      project.py        trace.pyc
editor.py       git_refs.pyc     project.pyc       wrapper.py
editor.pyc      git_ssh          pyversion.py      wrapper.pyc
error.py        hooks            pyversion.pyc
error.pyc       main.py          README.md
git_command.py  manifest_xml.py  repo
```

**Comment by corna** [comment] 2018-03-14 07:55
Some of the projects provided in the manifest don't have a lineage-15.1 branch, that's why `repo sync` fails.

https://github.com/LineageOS/android_vendor_qcom_opensource_location
https://github.com/LineageOS/android_vendor_nxp-nfc_opensource_frameworks
https://github.com/LineageOS/LineageOS/android_vendor_nxp-nfc_opensource_libnfc-nci
https://github.com/LineageOS/LineageOS/android_vendor_nxp-nfc_opensource_Nfc

They only have a `lineage-15.0` branch, not a `lineage-15.1`

**Comment by Man-with-Arrow** [comment] 2018-03-14 08:12
Ah. Thanks. I'm currently away from my PC, but I'm fairly sure I tried building with ``cm-14.1`` and it still threw the same error. 

I'll try building that and update when I'll have results.

**Comment by NadavCE** [comment] 2018-03-14 08:35
Thanks. I'll try building with ```lineage-15.0``` or ```cm-14.1```, and update here when I have results.

**Comment by corna** [comment] 2018-03-14 08:42
Note also `lineage-15.0` is even with `cm-14.1` for all these repos, so you can try to clone the repos, create a `lineage-15.1` branch, update your manifest and try a build.

**Comment by NadavCE** [comment] 2018-03-14 08:47
Sorry, I'm a bit new to git... You're saying I should fork these four repos to my own account, manually create/name the branch as ```lineage-15.1```, update my manifests.xml with the new links, and build?

**Comment by corna** [comment] 2018-03-14 09:02
Yep

**Comment by corna** [comment] 2018-03-14 09:03
Or you can also add `revision="lienage-15.0"` to the four repo in mata.xml

**Comment by NadavCE** [comment] 2018-03-14 10:45
@corna Thanks again. 

Another question - invisiblek's gist (with the needed manifests for mata) mentioned pulling some commits from gerrit. 

Do I fork said projects and apply the gerrit patches to them? Or is there a simpler way?

**Comment by NadavCE** [comment] 2018-03-14 20:06
Strangely, the issue still occurs. I even tried building with ```cm-14.1``` and got the same error. Same content as LINEAGE_15_1...

**Comment by corna** [comment] 2018-03-15 09:14
Can you upload here the `repo-*.log` file?

**Comment by NadavCE** [comment] 2018-03-15 13:54
@corna [Here you go.](https://github.com/lineageos4microg/docker-lineage-cicd/files/1815609/repo-20180314.log)

**Comment by corna** [comment] 2018-03-16 14:40
The log has lots of

> unable to access '...': gnutls_handshake() failed: The TLS connection was non-properly terminated.

It seems to be a network problem, try again

**Comment by NadavCE** [comment] 2018-03-16 16:40
No dice, still a bunch of ```unable to access '...': gnutls_handshake() failed: The TLS connection was non-properly terminated.```. A friend offered to try and build on his machine (different ISP, other side of town), and I'll try building on a different machine of my own. Will update with results.

**Comment by NadavCE** [comment] 2018-03-16 19:14
My other machine (same network) also failed, no TLS errors this time - lots of 404s though. I'll wait on my friend's update.

**Comment by NadavCE** [comment] 2018-03-17 11:01
@corna Friend has the same issue.

**Comment by ceptonit** [comment] 2018-07-17 18:30
@NadavCE

Have you ever had any luck on the build?
Hell, I can't even manage to build a regular Lineage build for this phone. I'd used Invisiblek's builds but they include gapps...

**Comment by nExXxuS** [comment] 2018-07-18 08:22
Closing that isse. Feel free to reopen whenever mata becomes official and it's still not building.

**Closed by nExXxuS** 2018-07-18 08:22 UTC

**Comment by NadavCE** [comment] 2018-08-04 21:56
@ceptonit No, I never did build successfully.

**Comment by tmolteno** [comment] 2018-11-02 07:44
I found this problem when working on the /e/ project (a lineage fork). After a few days of fruitless searching, I discovered that the problem is related to DNS resolution when using the default network bridge. It was resolved  (using docker-compose.yml) in my case by adding a line to the service.
            network_mode: "bridge"

**Comment by NadavCE** [comment] 2018-11-06 14:16
@tmolteno That sounds promising! I've installed Compose, how would I go about editing the service?

**Comment by tmolteno** [comment] 2018-11-06 23:43
@NadavCE  I have put a version of the script that I use here:
https://gitlab.com/tmolteno/e-docker-compose
The line is added to the service definition.
