### ISSUE TITLE
Disable April Fools pranks by default?

### ISSUE THREAD

**Issue by guixxx** [lineageos4microg/docker-lineage-cicd#9] opened 2018-04-05 13:13 UTC
Hello,

I've just updated LOS 14.1 to build `20180404` and I came across the [April Fools prank](https://www.reddit.com/r/LineageOS/comments/88ppge/changelog_17_building_blockchains_genuine/). I know that we can disable it by running `setprop persist.lineage.nofool true` in recovery, but I was wondering if it'd be possible to distribute LineageOS for microG with that property enabled by default, since it's useless and annoying.

Thanks.

**Comment by rugk** [comment] 2018-04-08 12:53
Come on, not everyone shares your opinion. This "fork" is about microG. No other changes should be included there. Ask/Complain at LineageOS itself, if you want to have that changed.

I do not support that change.

**Comment by guixxx** [comment] 2018-04-08 13:10
Please explain to me how keeping these "pranks" enabled will benefit anyone.

They're totally useless, not funny for most people (see the thread I've linked) and really annoying...

The LineageOS team won't stop doing them, it's been a trend since the CyanogenMod days, so it'd be useless to ask them.

I really want to know why would somebody be against this change, it literally has no downsides.

**Comment by guixxx** [comment] 2018-04-08 13:56
>Rather explain to LineageOS why you don't like any pranks and they do not benefit anyone.

Do I really have to? They already know the users hate these pranks. I mean, when you get [downvoted to hell](https://www.reddit.com/r/LineageOS/comments/89f76y/can_we_have_a_serious_talk_about_april_fools/dwqkdle/) trying to legitimize such "pranks", something must be wrong with it. So yes, they do already know people don't like it; and no, they won't stop doing it.

>Many people who may find it funny, obviously weon't find/complain in a thread.

If something is funny or not is totally subjective, sure. Can you at least acknowledge that most users don't like it?

>It has. I kinda like such pranks. 

You could enable them again if you're that sadistic, LOL.

>the previous ones at Cyanogenmod times were quite nice

[Sure](https://forum.xda-developers.com/nexus-6p/general/cyanogenmod-april-fools-joke-t3349532), putting "MOD" everywhere in the system can be funny for a few people.

>This "fork" is about microG. No other changes should be included there.

I disagree. Here's another argument in favor of disabling them: they're not trivial. They're completely removed in the next nightly build. So why not disable it by default?

>So be it. We have to live with it. Whether we like it or not.

Um, no? I'm literally proposing a way to disable them by default, we do not "have to live with them".

**Comment by rugk** [comment] 2018-04-08 16:56
I think you can hardly judge whether all LineageOS users like it by choosing reddit downvotes. 
The same logic applies: Everyone who likes it will not upvote that issue.

A good thing they could do, would be to include a question about this in their next survey. Again, however, it is a LineageOS thing.

> If something is funny or not is totally subjective, sure. Can you at least acknowledge that most users don't like it?

Actually, you are kinda contradicting yourself here. As it is subjective, not everyone will like the joke. Not everyone likes such jokes in LineageOS. But maybe some, maybe many, many most(?) people like them. Who knows…

> Here's another argument in favor of disabling them: they're not trivial. They're completely removed in the next nightly build.

Uh, yeah, that's a good argument…
So disabling them is hard, okay.

But you are drawing the wrong conclusion. If it is hard to disable them, the solution is not to disable them for all of them. :laughing: 
The solution is to make it easier for someone to disable them.

So we are back at the LinageOS. I think you are able to find a compromise, e.g. making it easier to disable with a setting in developer options. Or maybe setting up some rules for them (so that they are not scary). Or whatever…

In any case you need to direct that to LineageOS. Pursue them to change something. If you don't try, nothing will happen. Of course, they may not remove them completely, but maybe something else…? 
Remember, or for your case just imagine, people who like April fools (in software) and that the nature of such a fool is getting people surprised.

Also when we are talking about FLOSS sense, it makes no sense to do that in a fork. In case it really is behaviour that annoys people, then the fix needs to be in the upstream, i.e. a fix for many people. It should help many people and not the ones, who happen to download the microG fork, because it is microG.

**Comment by ArchangeGabriel** [comment] 2018-04-08 17:53
I mostly agree with you, but what if next year their prank is something about GApps which might mislead μG users into believing something bad happened?

**Comment by guixxx** [comment] 2018-04-08 18:34
>The same logic applies: Everyone who likes it will not upvote that thread.
>But maybe some, maybe many, many most(?) people like them. Who knows…

Dear god. You are either delusional or just one dense human being. I'm talking about the majority of users here. But if you're implying that the majority **did** like it, then please post some evidence, so that we can compare them the people who didn't like it. Here's 500+ people who didn't like it:

https://www.reddit.com/r/LineageOS/comments/89f76y/can_we_have_a_serious_talk_about_april_fools/

>So disabling them is hard, okay.

I didn't say disabling them was hard (even though it's not easy); When I said that such pranks are not **trivial**, I meant they're **completely useless** from any point of view (except if you're a sadistic developer), because they get removed in the next update no matter what.

>The solution is to make it easier for someone to disable them.

Jesus, **NO**. Do you have some kind of fetish on pranks? Legit question. So far you haven't provided me any solid reason to justify the usefulness of such pranks. On the other hand, I **am** justifying why they are completely useless (even though I thought that was obvious).

>people who like April fools (in software) and that the nature of such a fool is getting people surprised.

Nothing will stop them of being "surprised", just run `setprop persist.lineage.nofool false` after you flash the ROM if you like these pranks so much. It's actually laughable that your best argument to justify such anti-feature is because "there might be somebody who likes to be surprised".

>Pursue them to change something. If you don't try, nothing will happen.

Users have been asking devs to stop these pranks since the CM days. They've always responded by saying they were harmless "jokes"; Well, ants are harmless insects, but does that make them less annoying? No.

>Also when we are talking about FLOSS sense, it makes no sense to do that in a fork.

What?! Hello?!?! That's exactly the purpose of a fork: Fix or add stuff that upstream don't want to. If this dumb argument was actually valid, this repository shouldn't even exist to begin with, because signature spoofing is a feature which was constantly denied by the LineageOS devs. So let's follow your recommendation:

>In any case you need to direct that to LineageOS. Pursue them to change something. If you don't try, nothing will happen.

**Comment by felipe19930** [comment] 2018-04-08 18:51
I don't get it how someone can endorse this crap...

If the maintainers of this repo decide to not create a patch for the april fools, can somebody tell me how to do it? I assume is not that hard. I'll build the ROM myself.

**Comment by rugk** [comment] 2018-04-08 19:07
So you showed me some evidence that 500 users disliked that. LineageOS [has nearly 2 million _active_ users](https://stats.lineageos.org/), so the one who needs to show evidence is you. And yes, I know, you are not able to do so, because all users would have to be asked. That's why I'd suggest a survey.
Your sources are still biased. People complaining on reddit are people complaining there.

> I meant they're completely useless from any point of view (except if you're a sadistic developer)

It's getting philosophical now, but you may think April Fools are sadistic, but let's have a small look at why:
* [Everyone hates April Fools’ Day — so why does it endure?](https://www.theverge.com/2017/3/31/15076050/april-fools-day-pranks-jokes-terrible)
* [April Fools' Day! Why People Love Pranks](https://www.livescience.com/54259-april-fools-day-why-we-love-pranks.html)
* [Why Do We Celebrate April Fools' Day?](https://www.romper.com/p/why-do-we-celebrate-april-fools-day-7775)
* [more](https://lmddgtfy.net/?q=why%20do%20people%20make%20april%20fool%20jokes)

So as a question to you: Do you hate April 1st generally or what is actually the problem here?

> That's exactly the purpose of a fork

Not of this fork, unfortunately, sorry.

> this repository shouldn't even exist to begin with, because signature spoofing is a feature which was constantly denied by the LineageOS devs.

Indeed. And here you have it: The makers of this repo/microG people/whoever tried for several years, to submit patches to upstream (i..e LineageOS) to fix this. They declined, so this "fork" has emerged.

You quoted the correct part of my statement: "If you don't try, nothing will happen.". I did not see you tried to contact them.

But yeah, let's assume many other people did.

---
@ArchangeGabriel Okay, theoretically it could be "Google Apps will be installed on this device." or so. That's the scaries thing I can imagine for a microG user. The problem is: This is not funny for those, who already have them.
Or maybe it may be "Google will now control that device remotely." This would maybe really educational to Google Apps users (maybe microG users would rise :wink: ) and microG users know it is a prank cause they know they have no Google Apps, or so…

I think they realistically cannot make a joke about Google apps, because they some LineageOS users have them installed, some do not. It's hard to prank both groups.

Something like "Google Apps will stop working today, because your device is not certified." will rather amuse microG users, because they are not installed anyway.

Okay, they could check for Google Apps, and if there are none, show a message they will be installed (and vice-versa if not). Could be easily a false positive for microG users, so it would show the uninstall message. :laughing:

---

BTW I want to highlight that I don't think all their jokes are great. Particularly [the last one was likely way too scary](https://www.androidauthority.com/lineageos-april-fools-852705/) (I did not experience it, only read about it).
Also I do think LineageOS needs to do something about that and that they maybe need to improve the quality of their "jokes".

I just don't get why you can claim that all April jokes there were and will not be funny and no ones likes them.

----

But getting back to the "FLOSS sense" and a very **good news**: I should have clicked your reddit thread (and read it) earlier. Actually the one there proposed many things, and LineageOS devs have reacted and seem to plan some changes – and I really think thee are necessary:
* only appear on April 1st (**very** important, IMHO)
* can be disabled in the UI

So seems this is the right way.

As such there is still nothing to do for this "fork" here, IMHO. As said, it is not a problem for you to start your own fork (or as this project) some small patch applied.
However, I think it is quite superfluous when there will finally be a visible option in the settings to disable them. Then anyone can just disable them and life goes on… :smiley:

**Comment by rugk** [comment] 2018-04-08 19:14
Also:
* I do assume many people dislike that joke LineageOS put into there.
* I can assume that it freaked many people out.
* I do not assume "the majority" freaked out. Some people likely ignored it, some wondered, some got the joke. 500 people is a lot to complain and I'd say LineageOS has to react there. It's just their business, not LineageOS4MicroG's one. AFAIK LineageOS4microG wants to stay as close as possible to the official LineageOS.
* I generally do not assume what a majority does or likes, when I have no data about that.
* It also does not matter how much people like or dislike it.

**Comment by rugk** [comment] 2018-04-08 19:16
Also:
* I do assume many people dislike that joke LineageOS put into there.
* I can assume that it freaked many people out.
* I do not assume "the majority" freaked out. Some people likely ignored it, some wondered, some got the joke. 500 people is a lot to complain and I'd say LineageOS has to react there. It's just their business, not LineageOS4MicroG's one. AFAIK LineageOS4microG wants to stay as close as possible to the official LineageOS.
* I generally do not assume what a majority does or likes, when I have no data about that.
* It also does not matter how much people like or dislike it.

**Comment by LuccoJ** [comment] 2018-04-15 03:13
This fork also includes F-Droid, which has nothing to do with microG in itself. There is also discussion of disabling some proprietary APKs that some LineageOS 15 builds contain by default, which I would be in favor of.

This fork has always, at least according to its very own web page, stressed *usable free software*, with microG as the primary way to achieve it, and F-Droid as a natural adjunct.

So, at least, let's stop saying this fork should not modify *anything* except for adding microG... because it already has, and clearly a few users like that.

**Comment by rugk** [comment] 2018-04-15 07:59
> This fork also includes F-Droid, which has nothing to do with microG in itself. 

Not directly, but logically it has. It's basically the alternative to Google Play.

> There is also discussion of disabling some proprietary APKs that some LineageOS 15 builds

…because they are Google APKs. (and they don't work in this build anyway)

So these are not comparable to that change suggested here, which is toggling a setting completely unrelated to microG/Google. I mean you won't even find these April fool stuff/settings in the Google Apps/devices without LineageOS.

>  stressed usable free software

The April fool pranks are free software.

**Comment by nExXxuS** [comment] 2018-07-18 08:20
Closing this issue as upstream project apologized on bad aprils fool and it's unlikely they'll do the mistake again.

**Closed by nExXxuS** 2018-07-18 08:20 UTC
