### ISSUE TITLE
microG GmsCore not updating through F-Droid / showing up as "UnifiedNlp (no GAPPS)"

### ISSUE THREAD

**Issue by bananer** [lineageos4microg/docker-lineage-cicd#266] opened 2022-02-14 11:35 UTC
With a default install of lineageos4microg, the microG GmsCore package is not automatically updating through F-Droid and neither can it easily be found there.

This issue has been brought up in various places and I did some digging over the past few days to get to the bottom of this. Here's what I found out.

### F-Droid and its repositories

The F-Droid project maintains its own list of applications, which they compile themselves, but the F-Droid client allows one to add multiple such repositories. By default, F-Droid comes with the official F-Droid repository and a repository from the Guardian Project configured.

F-Droid client contains a mechanism which can be used by ROMs packaging it to insert additional repositories into its configuration by including a file called `additional_repos.xml`. Lineageos4microg uses this mechanism to insert the [microG repository](https://microg.org/fdroid.html), which should - in theory - enable GmsCore to be updated independently from the rest of the ROM.

### UnifiedNlp

UnifiedNlp is a component of microG which replaces or extends Google's location provider. It is built into GmsCore but also distributed separately as a versions for devices [with](https://f-droid.org/en/packages/org.microg.nlp/) and [without Gapps](https://f-droid.org/en/packages/com.google.android.gms/) installed, in F-Droids repository (the official repo, not the microG one).

UnifiedNlp (no GAPPS) has the package ID `com.google.android.gms`, which is the same as microG GmsCore, and this is where the problem begins.

### F-Droid: Duplicate package IDs and repository priorities

While a single F-Droid repository should never contain apps with the same package ID, it is possible, like in our case, for multiple repositories to supply a package with the same ID. To handle this, F-Droid assigns a numeric priority to every repository and for duplicate IDs is shows the app details (Name, screenshots, ...) from the repository with the highest priority. Notably F-Droid shows versions (installable Apks) from all repositories, as long as they can currently be installed on the device (matching signature, and other requirements).

F-Droid's built-in repositories are assigned priorities starting from `1` and increasing, every repository added by a user manually gets the next highest priority. However, repositories added via `additional_repos.xml` are prioritised as `0`.

This explains why users of lineageos4microg will not find an entry for "microG GmsCore" but only "UnifiedNlp (no GAPPS)" in F-Droid. Automatic updates by F-Droid are triggered through the setting `CurrentVersionCode` in the repo with highest priority, where on lineageos4microg you also get the value for "UnifiedNlp (no GAPPS)".

### microG signature spoofing

It was a bit surprising to me that signature spoofing does not actually cause any of this. In the microG repository the faux signature is (correctly) listed which is why F-Droid actually shows the GmsCore versions under the UnifiedNlp entry.

### Workarounds for users

If you've read this far, you might have figured some of these out already:

* Manually install a GmsCore update by navigating to "UnifiedNlp (no GAPPS)" in F-Droid, opening the "Versions" dropdown and selecting the newer version to install. By default, this will only show you versions with matching signatures (i.e. those which are actually GmsCore).
* Enabling "Unstable updates" in F-Droid should enable microG automatic updates, however it would also cause other apps to update to instable versions.
* Disable the official F-Droid repository. This removes the duplicate package and lets GmsCore (aka. microG Services Core) show up as expected. However, this also removes access to all other apps on F-Droid.
* Removing the microG repository and adding it back manually. This gives it a higher priority than all other repositories, which fixes both the app details view and auto updates for GmsCore.

### What could be done in F-Droid to resolve this problem?

* Assign higher priorities to repos added with `additional_repos.xml`. This idea was rejected: [fdroidclient #2045](https://gitlab.com/fdroid/fdroidclient/-/issues/2045)
* If an app is installed with multiple repos providing its package id, use the metadata details for the one with a matching signature. This is the desired solution ([fdroidclient #1566](https://gitlab.com/fdroid/fdroidclient/-/issues/1566)). I looked into the code a bit and unfortunately this is rather complicated to implement. F-Droid stores most of its data in SQLite and uses many queries which simply order the repositories by priority.
* Use the signing key of an app as its unique identified, instead of the package ID. Discussed as [fdroidclient #702](https://gitlab.com/fdroid/fdroidclient/-/issues/702), seems controversial.
* Removing the `CurrentVersionCode` for UnifiedNlp from their repository might enable auto-updates again. It seems this was implemented as a workaround some time ago but then reverted. [I've requested it to be restored here](https://gitlab.com/fdroid/fdroidclient/-/issues/1904#note_841538198).
* Remove "UnifiedNlp (no GAPPS)" from their repository. Its usecase is not really obvious, I doubt it has many users and it was last updated 5 years ago. I don't know how the removal process works, maybe @martin-v as the creator can request that?

### What could be done in lineageos4microg to resolve the problem?

* Fork F-Droid client to give the microG repo a higher priority. 
* ...?

**Comment by bananer** [comment] 2022-02-15 13:11
> Does it make a difference if it's updated via the prebuilt bundeled lineages4microg image or via F-Droid?

I don't think you need to worry about that. Android will pick the latest version from either system or data partition, i.e. included in ROM or installed by user. The app's data (settings, ...) are always stored on the data partition.

This mechanism is the same on stock ROMs where system apps (like gapps) can either be updated through play store or through system updates. Never heard anybldy complaining about that 😀

**Comment by defkev** [comment] 2022-11-08 15:42
I just ran into the same problem after seeing microG got an update a couple of weeks ago and F-Droid displaying nothing unless i disabled the F-Droid repository.

imho this should be fixed on F-Droid's end by moving the conflicting **UnifiedNlp (no GAPPS)** to the **F-Droid Archive** repository considering there hasn't been a new release in 5+ years.

Just my 2 cents

**Comment by LuccoJ** [comment] 2023-01-19 04:06
Thanks for doing this research. I've brought up this issue sometimes with F-Droid people, but they either didn't see an issue or they didn't agree with my proposed solution (moving the little-used package to the Archive repository was my first thought).

**Comment by st3rox** [comment] 2023-06-26 05:08
Hey I think this issue is finally fixed!
com.google.android.location goes to unifiednlp (no gapps) 
And com.google.android.gms goes to microg services core
Can others confirm this in their fdroid?

**Comment by defkev** [comment] 2023-06-26 06:10
com.google.android.gms is no longer in F-Droid: https://f-droid.org/en/packages/com.android.google.gms/ -> 404

This may (or may not i dunno) have something to do with the location stack rewrite in microg 0.2.28 deprecating UnifiedNLP

**Comment by nidico** [comment] 2023-12-21 21:47
Right, I guess this can be closed then.

I noticed that GmsCore version 0.2.27.223616 is still the suggested version due to all newer versions being considered beta, but this needs to be addressed in the metadata of the microG fdroid repo in case it's not intended. I created issue microg/GmsCore#2128 in order to clarify.

**Comment by ale5000-git** [comment] 2023-12-22 19:59
They were marked as beta as there were some regressions from version 0.2.28 and highers.
The version 0.3.0 shouldn't have much regressions left I think.

**Comment by petefoth** [comment] 2024-04-04 17:49
I'm going to close this issue. As far as I know, microG does get updated by F-Droid. 0.2.nn is still the 'stable' version. 0.3.nn can be installed by enabling 'Allow beta updates` for GmsCore in F-Droid

**Closed by petefoth** 2024-04-04 17:49 UTC
