### ISSUE TITLE
vayu - no internet for microg, battery drain

### ISSUE THREAD

**Issue by andrzej-gmt** [lineageos4microg/docker-lineage-cicd#434] opened 2023-06-26 15:42 UTC
I have updated my Poco X3 Pro with June release. Previously I had April release, which worked well.
After update I noticed two problems:
- battery drain got bigger, I had to charge very often,
- I couldn't perform login to Google account, microg showed no internet access to www.googleapis.com.

Actually there was no network problems, other programs could access internet.
I have preformed whip and clean reinstall of June release, but network problem for microg persisted.
I have looked for similar issue and found this: https://github.com/lineageos4microg/docker-lineage-cicd/issues/404

**Comment by andrzej-gmt** [comment] 2023-06-29 10:10
I'm not sure if this is a right place to report issue. Just to finish, I'd like to add:

Before update I used microg 0.2.28. I think LOS update comes with microg 0.2.27. I wonder if this kind of downgrade works correctly. I have removed microg updates after noticing problems, but it didn't help.

I use SeedVault backup. I wonder if SeedVault could corrupt microg settings after clean reinstall.

**Comment by petefoth** [comment] 2023-08-17 19:56
Closing - duplicate of #404

**Closed by petefoth** 2023-08-17 19:56 UTC
