### ISSUE TITLE
Wish for public build logs or at least status

### ISSUE THREAD

**Issue by ldoolitt** [lineageos4microg/docker-lineage-cicd#71] opened 2020-02-16 18:15 UTC
It seems two L4M 16.0 builds in a row for payton have failed, and as an outsider I have no clue why.  The corresponding logs from upstream LineageOS are OK.

The real issue is that there's no status page that can tell me what's going on.  All I can see is that the latest download at https://download.lineage.microg.org/payton/ is lineage-16.0-20200130-microG-payton, where we should be up to 20200213 by now.

This is in contrast with upstream LineageOS, where https://www.lineageoslog.com/16.0/payton seems to tell me a lot about the build process, and payton in particular seems to be building fine.

I can passively wait another week, just in case the next build succeeds. It would be a lot more satisfying to know why the last build failed, what action has been taken to fix it, and what if anything I could do to help.

The specific topic of recent payton build failures got posted on reddit
https://www.reddit.com/r/MicroG/comments/f3z1m2/no_february_builds_for_payton_moto_x4/
but I'd like to go meta on it.

**Comment by ldoolitt** [comment] 2020-02-22 04:04
Another week has gone by, and still no payton builds or hints as to what's going on behind the curtain.

There are 109 devices with L4M 16.0 downloads available at https://download.lineage.microg.org/.
After ignoring the three devices (klimtwifi, lettuce, violet) that are not recognized as current by upstream LineageOS, 101 of the 106 remaining devices had an artifact built as part of the last weekly build run.  That run lasted from 2020-02-17 00:00 to 2020-02-21 22:33, over 118 hours of wall-clock time, plodding through the device list in alphabetical order.  :-o

That leaves the following four or five "missing" builds, listed here with their last successful build date:

* 20200109 nash
* 20200130 payton
* 20200211 dipper
* 20200211 gemini
* 20200215 zl1  (maybe I'm just impatient on this one)

Surely those 106 build logs exist somewhere?
95% success rate is pretty good, unless one of the failures represents the phone in your pocket!  :-(
All five of the listed builds are working fine for upstream LineageOS.

Questions about individual failed builds sometimes show up on the xda-developers forum.
kendallgreen asked about the "mssing"  nash build on Feb. 1 (https://forum.xda-developers.com/showpost.php?p=81651899&postcount=1747) but nash builds are still MIA three build cycles later.

Maybe I should ask this question on the XDA forum?  So far their anti-spam processes have rebuffed me.

**Comment by Abogical** [comment] 2020-02-25 22:46
I'm payton as well :confused:. Can you try building LineageOS with MicroG and see if an error pops up? Maybe it will explain the lack of builds.

**Comment by ldoolitt** [comment] 2020-02-26 05:30
> Can you try building LineageOS with MicroG and see if an error pops up? 

Not at this time.  Maybe I can try setting up for it after another week.
BTW, last week's zl1 build finally did finish successfully.

**Comment by hhoefener** [comment] 2020-03-08 10:05
Tried building LineageOS for microG for payton yesterday but failed due to limited space on my disk :-(
It occupied > 230GB. Perhaps someone else could try. It is very easy using the docker from dockerhub: Just mount some empty folders to it as shown in the readme, everything else will be done automatically. Just bring along some time...

**Comment by TobeStokes** [comment] 2020-03-08 14:57
> Tried building LineageOS for microG for payton yesterday but failed due to limited space on my disk :-(
> It occupied > 230GB. Perhaps someone else could try. It is very easy using the docker from dockerhub: Just mount some empty folders to it as shown in the readme, everything else will be done automatically. Just bring along some time...

I tried building it this weekend also.  I had issues with storage running out too but once I gave it 200GB then it was not a problem anymore.  My build occupied about 150GB of space on a 200GB VM drive.   

I posted in detail about it here:  https://github.com/lineageos4microg/l4m_website/issues/43

The gist of it is the docker build fails with no info about why, just says "build failed for payton"

If anybody can tell me a way to get more verbose output from the docker run command I'll try again and see what the output says.  I've tried the `docker logs` command, and running `docker events&` in the background with no improvement of verbosity about the error.

**Comment by exzombie** [comment] 2020-03-08 18:14
Maybe this issue should be renamed as it is primarily about the payton build. Although having public build logs would be nice too.

**Comment by wismann83** [comment] 2020-03-21 18:14
The lineageos4microg github page has a repo for 'build_stats'.
In theory this should provide us with a REST interface for build stats.
Can anyone comment on whether this is currently running, reachable from the internet and which IP address and port to use?
I tried the obvious combinations and received only HTTP 301.

RFC:
It should be easy to modify the dockerfile in a way that, if the build fails, the log is copied to the output directory instead of the zip (I don't think we need build logs on successful builds).
What do you think?

**Comment by hhoefener** [comment] 2020-03-31 12:34
Any news on this? I followed the discussion on [xda](https://forum.xda-developers.com/android/software/lineageos-microg-t3700997) but don't really get what the problem is or whether someone is working on it. If I can help somehow, please let me know. I'm staring to feel a bit uneasy with a 2 month out-of-date phone...

**Comment by onionjake** [comment] 2020-04-03 17:40
I was able to locally build `nash` just fine with the docker image.  I am willing to help debug the current build servers or host a build server for the project.  @corna What can we do to help?

**Comment by DPTJKKVH** [comment] 2020-04-11 07:19
Lithium (Xiaomi MiMix) builds seem to have failed two weeks in a row as well.

I would buy the required hardware (mainly storage) to build myself and see what's wrong but I wouldn't be able to use the builds because of the different signing key. So it would make more sense to donate to the official build servers maintenance.  

@ldoolitt I saw your posts on XDA. Will you be running the build servers in future? Do you know whats causing build failures with so many devices lately? Is it related to LineageOS switching to 17.1?

**Comment by TobeStokes** [comment] 2020-04-13 18:42
> 
> 
> Lithium (Xiaomi MiMix) builds seem to have failed two weeks in a row as well.
> 
> I would buy the required hardware (mainly storage) to build myself and see what's wrong but I wouldn't be able to use the builds because of the different signing key. 

You can run a script over adb to change your signing keys to your own build or back to official.  I'm running my own build since last month, after a bit of trial and error.  All good now, but I may have to build again soon since April patches are probably out, and there are still no new builds published at https://download.lineage.microg.org/payton/

**Comment by DPTJKKVH** [comment] 2020-04-13 18:50
@TobeStokes 

Hey thanks for the suggestion!

This sound like I need one of those flashable "migration.zip" files.

I happen to have one of those for bullhead (Google Nexus 5x). Can I just take this and swap my keys or do the migration.zip files need to be customized for each device?

**Comment by TobeStokes** [comment] 2020-04-18 14:27
> @TobeStokes
> 
> Hey thanks for the suggestion!
> 
> This sound like I need one of those flashable "migration.zip" files.
> 
> I happen to have one of those for bullhead (Google Nexus 5x). Can I just take this and swap my keys or do the migration.zip files need to be customized for each device?

I'm not sure about the flashable zip files, sorry.  I used the key migration instructions from the official LineageOS site here:  https://wiki.lineageos.org/signing_builds.html#test-keys-to-your-own-release-keys-or-vice-versa

To get mine done I had to dig a little deeper into the folder structure of the build's output, but the directories mentioned in those instructions are present, just under some extra folders with the LOS4microG Docker output.  I think I documented this on the other issue thread about Moto X4 updates that I started.  

I ran the export keys script to get my keys in the terminal output, then copied the keys' data from each line to the appropriate "Release keys" places in the migration script.  It was a little bit tedious but that may be necessary to do it carefully & accurately.  Once that was done and I ran the script from TWRP recovery over ADB then my custom build with custom keys installed just fine.  I made another build yesterday with April security updates and it installed just like a normal update with no trouble.  Since my phone is already on my custom keys, it was a one-time changeover thing, as long as I keep using the same keys to build future updates.

**Comment by DPTJKKVH** [comment] 2020-04-18 14:40
@TobeStokes Thank you very much for the detailed explanation! I now feel comfortable enough to go ahead and try to build my own ROM with docker. :)

**Comment by DPTJKKVH** [comment] 2020-04-24 10:58
@TobeStokes May I ask one last stupid question?

Thanks to you, evan-goode and SolidHal I managed to create a working docker image and currently run it without getting any errors so far. (Hope I don't jinx it...)

Does the docker bild process stop automatically after the ROM has been created? There is no progress indicator so I have no idea how long building one rom takes and if it exits with some kind of success message.

**Comment by TobeStokes** [comment] 2020-08-20 18:48
FYI there is a new build for Payton on the LineageOS for MicroG download site now.  It's Lineage 17.1

**Comment by petefoth** [comment] 2023-07-27 10:12
This is addressed in
#383 which is closed, as the build progress can be monitored on the dedicated Matrix channel https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net
#455

**Closed by petefoth** 2023-07-27 10:12 UTC
