### ISSUE TITLE
Bootloop after formatting /data with LineageOS 17.1 on XZ2 Compact

### ISSUE THREAD

**Issue by K4sum1** [lineageos4microg/docker-lineage-cicd#526] opened 2024-01-13 14:31 UTC
I've been compiling LineageOS 17.1 for my XZ2 Compact, and if I format /data in LineageOS Recovery with a MicroG compiled ROM installed, it causes the device to bootloop. It works fine if I compile without MicroG. I can't seem to get a logcat, adb logcat gives me an inaccessible or not found error.

**Comment by K4sum1** [comment] 2024-01-16 04:11
This does not happen if I use microk5's microg installer. Maybe a newer app version hates my phone, or I'm doing it wrong, or 17.1, but afaik the XZ1C 17.1 MicroG ROM still works fine, haven't tried self building it though.

**Comment by K4sum1** [comment] 2024-01-18 13:53
I tried building for XA2 with the same config. That phone also bootloops.

**Comment by petefoth** [comment] 2024-01-19 06:53
OK, I have lost track of what your problem is ☹️   

Your original post says:
> I've been compiling LineageOS 17.1 for my XZ2 Compact, and if I format /data in LineageOS Recovery with a MicroG compiled ROM installed, it causes the device to bootloop. 

So 
1. You have an up-to-date (version 20.0) los4microg XZ2C ROM installed, built by us, downloaded from [here](https://download.lineage.microg.org/xz2c/).
2. You make a 17.1 build.
3. You format the data partition using the currently installed recovery - what version is that recovery? Where did you get it? The latest recovery built by us for this device is [lineage-20.0-20240101-microG-xz2c-boot.img](https://download.lineage.microg.org/xz2c/lineage-20.0-20240101-microG-xz2c-boot.img)
4. You install your built los4microg 17.1 ROM over the installed los4microg 20.0 ROM, using the currently installed recovery, following the LineageOS installation instructions [here](https://wiki.lineageos.org/devices/pioneer/install/#), for XZ2C.
5. You try to boot into the 17.1 ROM.
6. The  phone bootloops.

Is that what happens? 

If so, then I guess the recovery you have installed is not compatible with the older build, perhaps because newer builds have different partition layout. If you really want an old, out-of-date version installed, then you may have to find an old, out-of-date recovery (or build it yourself). Either way, this project is not in a position to support old, out of date builds. You can try
asking in the [XDA Forum Thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/) to see if anyone there can help.

If I have misunderstood what you are doing, then please explain, step by step, what you are doing, including ROM and recovery versions, and where you obtained the recovery.

Thanks

**Comment by K4sum1** [comment] 2024-01-19 14:30
> If I have misunderstood what you are doing, then please explain, step by step, what you are doing, including ROM and recovery versions, and where you obtained the recovery.

So I've done something and it basically means there's something I did wrong, but I have no idea what. My XZ1C (lilac) is my main phone, and I decided to compile LineageOS 17.1 with MicroG for it, and it has the same issue. I then tried this LineageOS 17.1 with MicroG (https://drive.google.com/drive/folders/1rMtLfXbpdlNusvd2AFt_OPWPW_LZehTZ) and it just works. I am building from the same repo as the linked ROM. (https://github.com/Flamefire/lineageos_lilac) For MicroG, since instructions aren't listed I just did export WITH_GMS=true to build with MicroG. Is there a step I missed somewhere for getting MicroG working? The only extra thing I have is this (https://github.com/kumikooumae/android_vendor_extra) which I don't think should affect anything. I have also found that if I add MicroG using an installer the ROM gets all buggy and certain parts of settings like Bluetooth or the Battery Manager freeze the settings app. The linked ROM on Google Drive is completely fine with no issues.

**Comment by petefoth** [comment] 2024-01-19 19:12
OK. Thanks for explaining.

That LineageOS  ROM is not an official ROM built by us. XZ1C is not officially supported by LineageOS so we don't make builds for it, or support it.
 
But I may be able to help on a personal basis. I know Flamefire's unofficial ROMs - XZ1C is my main phone, and I ran Flamefire's ROMs for a while before moving on to Whatwurst's unofficial 20.0 ROM, for which I made a MicroG build, and then on to unofficial IodéOS..

I also tried in the past to build from Flamefire's sources, but my builds used to bootloop in the same way as yours. The root cause - which I never managed to fix - was that Flamefire did not publish the vendor binary blobs, the device tree code expected certain blobs to be present: if those blobs were not present at runtime, the device would bootloop. It appears he does now publish them: your bootloop problem **_may_** be because of a mismatch between the blobs that are in the repos, and the blobs thatbare actually needed for the device to run.

I was trying to build because, at that time Flamefire did not make microG builds, only 'normal' LineageOS. I stopped trying when Flamefire started making MicroG builds himself.

I don't know why you want to make your own 17.1 MicroG ROM, when Flamefire already makes and publishes MicroG builds. If you do, and if it is not working for you, then the place to ask is in the [XDA Forum thread for Flamefire's 17.1, 18.1 & 19.1 builds](https://xdaforums.com/t/rom-lineageos-17-18-19-unofficial-update-2023-12-25.4308295/unread).

I'm going to close this issue, as it is nothing to do with this project (which deals with making microG builds of devices officially supported  by LOS). I will try to answer any further questions you may have, but really you have a better chance of solving you problem in the XDA forum thread.

Good luck

**Closed by petefoth** 2024-01-19 19:12 UTC

**Comment by K4sum1** [comment] 2024-01-19 20:06
> I also tried in the past to build from Flamefire's sources, but my builds used to bootloop in the same way as yours. The root cause - which I never managed to fix - was that Flamefire did not publish the vendor binary blobs, the device tree code expected certain blobs to be present: if those blobs were not present at runtime, the device would bootloop. It appears he does now publish them: your bootloop problem **_may_** be because of a mismatch between the blobs that are in the repos, and the blobs thatbare actually needed for the device to run.

Do you know for a fact it is the same issue? Why would it work fine without MicroG without these missing blobs? If I tried using the wrong firmware/blobs it just wouldn't compile for me in the past? Only until I tried Customized DE did it actually compile.

What about the XZ2C? This looks to be the same issue on that phone. For blobs I used luk1337's muppets xml. I also tried building for the XA2, another phone I have, and still same issue.

> I don't know why you want to make your own 17.1 MicroG ROM, when Flamefire already makes and publishes MicroG builds. If you do, and if it is not working for you, then the place to ask is in the [XDA Forum thread for Flamefire's 17.1, 18.1 & 19.1 builds](https://xdaforums.com/t/rom-lineageos-17-18-19-unofficial-update-2023-12-25.4308295/unread).

https://github.com/Flamefire/lineageos_lilac/issues/5
and
https://github.com/Flamefire/lineageos_lilac/issues/4

> I'm going to close this issue, as it is nothing to do with this project (which deals with making microG builds of devices officially supported by LOS). I will try to answer any further questions you may have, but really you have a better chance of solving you problem in the XDA forum thread.

Again, what about the XZ2C? That is the main device I want to build for. XA2 is also another one I want to build for, but I think I want to ultimately go for 15.1 on the XA2 since that is supported there.

**Comment by petefoth** [comment] 2024-01-19 20:31
I'm sorry, but I can't help any more. You are trying to build very old versions because you don't like the 'recents' functionality. If that's what you want to do, then that's fine, but it's not something this project supports or can help with.

For XZ1C,  Flamefire makes unofficial microG builds for 17.1, 18.1, 19.1 using his sources. I make unofficial 20.0 microG builds using [Whatawurst's sources](https://github.com/whatawurst/). Flamefire has tried to help you but it seems that's not good enough for you.

For XA2 & XZ2C, this project makes official 20.0 microG builds using the LOS sources and TheMuppets repos. For pioneer, we even have the most recent 19.1 build  available [here](https://download.lineage.microg.org/pioneer/) (but it won't be there much longer). Again it seems that is not good enough for you. I have tried to help as much as I can, but it looks like, from here on, you are on your own. My suggestion would be use an up-to-date version. If you don't want to do that, that's fine, but don't expect others to solve the problems you are causing  for yourself.

I am locking this issue - the discussion is going nowhere, and there are more important issues for this project to deal with.
