### ISSUE TITLE
Failed to install addons using recovery, requires additional space.

### ISSUE THREAD

**Issue by nyangnyong** [lineageos4microg/docker-lineage-cicd#486] opened 2023-10-02 05:12 UTC
Tried to install **MinAddon-Playstore** and **MinAddon-AuroraServices** using recovery but failed.
Download link: [MinMicroG](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2023.07.29)

It works on **crDroid** but not on **LineageOS for microG**.

Here's the log: [recovery.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/12779717/recovery.log)

### MinAddon-Playstore
> [  307.964202] Zip File is /sideload/package.zip
> [  307.964301] Bootmode is false
> [  307.964496]  
> [  307.964508] Mounting early
> [  307.974856] mount: '/system' not in fstab
> [  307.976872] Mountpoint /system mounted (auto)
> [  308.070390] Mountpoint /mnt/system mounted (manual /dev/block/mapper/system)
> [  308.083739] mount: '/dev/block/platform/bootdevice/by-name/userdata'->'/data': Invalid argument
> [  308.200017] unknown fuse request opcode 2016
> [  308.201380] Archive:  /sideload/package.zip
> [  308.201420]   inflating: /tmp/MinMicroG/defconf
> [  308.219569] unknown fuse request opcode 17
> [  308.233932] unknown fuse request opcode 17
> [  308.234055] mount: '/mnt/system' not in /proc/mounts
> [  308.236899] Mounted /mnt/system RW
> [  308.259718] unknown fuse request opcode 2016
> [  311.624977] Archive:  /sideload/package.zip
> [  311.625019]   inflating: /tmp/MinMicroG/INSTALL.md
> [  311.625034]   inflating: /tmp/MinMicroG/defconf
> [  311.625047]   inflating: /tmp/MinMicroG/LICENSE
> [  311.625060]   inflating: /tmp/MinMicroG/META-INF/com/google/android/updater-script
> [  311.625073]   inflating: /tmp/MinMicroG/META-INF/com/google/android/update-binary
> [  311.625085]   inflating: /tmp/MinMicroG/system/etc/permissions/com.android.vending.xml
> [  311.625097]   inflating: /tmp/MinMicroG/system/priv-app/Phonesky/Phonesky.apk
> [  311.625109]   inflating: /tmp/MinMicroG/README.md
> [  311.625121]   inflating: /tmp/MinMicroG/util/script-addon.sh
> [  311.625134]   inflating: /tmp/MinMicroG/util/func-defconf.sh
> [  311.634976] Removing duplicates
> [  311.737200] Debloating
> [  311.940492] `Pack size is 62`
> [  311.952406] unknown fuse request opcode 17
> [  311.958319] `Free space in /mnt/system is 2`
> [  312.120407] umount: /system: Invalid argument
> [  312.185020] umount: /data: Invalid argument
> [  315.808091] ERROR:   recovery: Error in /sideload/package.zip (status 1)
> [  315.940624]
> [  316.058757] W:failed to read uncrypt status: No such file or directory
> [  316.062648] I:current maximum temperature: 41900
> [  316.062768] I:/sideload/package.zip
> [  316.062774] 0
> [  316.062776] time_total: 17
> [  316.062778] retry: 0
> [  316.062781] error: 21
> [  316.062783] temperature_start: 41752
> [  316.062785] temperature_end: 41900
> [  316.062787] temperature_max: 41900
> [  316.062789]
> [  316.063088] I:Command 0 finished with 0
> [  317.104218] minadbd W 10-02 04:17:46   431   431 sockets.cpp:279] timeout expired while flushing socket, closing
> [  317.104416] minadbd I 10-02 04:17:46   431   436 minadbd_services.cpp:159] revents: 16
> [  317.153321] I:Socket has been closed
> [  317.203504]
> [  317.203537] Install completed with status 1.
> [  317.402930] Installation aborted.

### MinAddon-AuroraServices

> [  365.247354] Zip File is /sideload/package.zip
> [  365.247473] Bootmode is false
> [  365.248178]  
> [  365.248213] Mounting early
> [  365.260274] mount: '/system' not in fstab
> [  365.262241] Mountpoint /system mounted (auto)
> [  365.344818] Mountpoint /mnt/system mounted (manual /dev/block/mapper/system)
> [  365.354659] mount: '/dev/block/platform/bootdevice/by-name/userdata'->'/data': Invalid argument
> [  365.464575] unknown fuse request opcode 2016
> [  365.465872] Archive:  /sideload/package.zip
> [  365.465898]   inflating: /tmp/MinMicroG/defconf
> [  365.487552] unknown fuse request opcode 17
> [  365.503426] unknown fuse request opcode 17
> [  365.503575] mount: '/mnt/system' not in /proc/mounts
> [  365.506970] Mounted /mnt/system RW
> [  365.530906] unknown fuse request opcode 2016
> [  365.685043] Archive:  /sideload/package.zip
> [  365.685078]   inflating: /tmp/MinMicroG/INSTALL.md
> [  365.685089]   inflating: /tmp/MinMicroG/defconf
> [  365.685097]   inflating: /tmp/MinMicroG/LICENSE
> [  365.685105]   inflating: /tmp/MinMicroG/META-INF/com/google/android/updater-script
> [  365.685114]   inflating: /tmp/MinMicroG/META-INF/com/google/android/update-binary
> [  365.685122]   inflating: /tmp/MinMicroG/README.md
> [  365.685130]   inflating: /tmp/MinMicroG/system/etc/permissions/com.aurora.services.xml
> [  365.685138]   inflating: /tmp/MinMicroG/system/priv-app/AuroraServices/AuroraServices.apk
> [  365.688905] Removing duplicates
> [  365.792238] Debloating
> [  365.882981] `Pack size is 3`
> [  365.897283] unknown fuse request opcode 17
> [  365.903849] `Free space in /mnt/system is 2`
> [  366.043920] umount: /system: Invalid argument
> [  366.097838] umount: /data: Invalid argument
> [  371.284501] ERROR:   recovery: Error in /sideload/package.zip (status 1)
> [  371.400383]
> [  371.518675] W:failed to read uncrypt status: No such file or directory
> [  371.522544] I:current maximum temperature: 41752
> [  371.522650] I:/sideload/package.zip
> [  371.522656] 0
> [  371.522658] time_total: 11
> [  371.522661] retry: 0
> [  371.522663] error: 21
> [  371.522665] temperature_start: 41157
> [  371.522667] temperature_end: 41752
> [  371.522669] temperature_max: 41752
> [  371.522671]
> [  371.522934] I:Command 0 finished with 0
> [  372.551415] minadbd W 10-02 04:18:42   548   548 sockets.cpp:279] timeout expired while flushing socket, closing
> [  372.552592] minadbd I 10-02 04:18:42   548   553 minadbd_services.cpp:159] revents: 16
> [  372.591426] I:Socket has been closed
> [  372.637479]
> [  372.637530] Install completed with status 1.
> [  372.812808] Installation aborted.

Device: Redmi 9 (Lancelot).

**Comment by st3rox** [comment] 2023-10-02 05:29
What do these addons do that isn't already a feature of lineageos for microg?

**Comment by petefoth** [comment] 2023-10-02 06:32
Firstly
- which device are you using?
- which build of LineageOS for MicroG?
- which recovery are you using?

Secondly, from [the '[Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support)' section of our README](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support)
> The LineageOS for MicroG project is not in a position to offer much
> by way of technical support:
> 
> *    the number of active volunteer maintainers / contributors is
> very small, and we spend what time we have trying to ensure that the
> process of making regular builds keeps going. We can generally
> investigate problems with the build tools, but not with the ROM
> itself;
> 
> *    we don't have access to any devices for testing / debugging

and 

> The [project issue tracker](https://github.com/lineageos4microg/docker-lineage-cicd/issues) is mostly for tracking problems with the Docker build tool. It is not intended for tracking problems with installing or running the LineageOS for MicroG ROM.

I wll close this issue in a couple of days
and

> For any problems, with building, installing, or running LineageOS for MicroG, we recommend that you ask for help in [the XDA Forum thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/) or in device specific [XDA forum threads](https://forum.xda-developers.com/). The LineageOS for MicroG forum thread is not maintained by us, but there are many knowledgeable contributors there, who build and run the LineageOS for MicroG ROM on a wide variety of devices.

**Comment by petefoth** [comment] 2023-10-02 06:59
> It is clearly written that I am using Redmi 9 (Lancelot). :)

Sorry - I didn't spot that: too early on the day, and not enough coffee yet :)

> I created an issue here because I felt it had something to do with #358

It **_may_** be something to do with that issue, but that is closed as 'Won't fix' and 'Not a bug'
 
> If not, it's up to you to close the issue. Sorry if it just wastes your time.

It's not about wasting my time, it's that we - the project maintainers - don't have the time or resources to investigate issues like this, and I don't want you wasting ***your*** time waiting for a 'fix' here that probably isn't going to happen. Yoy have more chance of getting help if you post in the XDA Forum thread, where there are many knowledgeable users who ***may*** be able to help you.

**Closed** 2023-10-02 07:09 UTC
