### ISSUE TITLE
The Updater always shows updates even if the lastest update has been installed.

### ISSUE THREAD

**Issue by h0cheung** [lineageos4microg/docker-lineage-cicd#103] opened 2020-08-26 07:24 UTC

**Comment by spolack** [comment] 2020-08-27 12:20
What LineageOS version are you using?

**Comment by h0cheung** [comment] 2020-08-28 05:34
@spolack 17.1-20200825-microG-dipper

**Comment by kurt-by** [comment] 2020-09-05 17:20
Same issue with 16.0-20200816-microG-klte

**Comment by smac89** [comment] 2020-09-22 07:49
Same issue for mata

**Comment by kurt-by** [comment] 2021-09-08 10:45
This is a duplicate of https://github.com/lineageos4microg/docker-lineage-cicd/issues/171

**Closed** 2021-09-09 13:35 UTC
