### ISSUE TITLE
Builds for fajita (OnePlus 6T)?

### ISSUE THREAD

**Issue by prg318** [lineageos4microg/docker-lineage-cicd#73] opened 2020-04-03 02:44 UTC
Is there any particular reason that there are not builds for fajita (OpenPlus 6T)?  Fajita is currently officially supported by LineageOS (https://download.lineageos.org/fajita).

I haven't yet tried to build l4m for fajita, but it seems other people have been able to in the past (https://forum.xda-developers.com/oneplus-6t/development/rom-lineageos-microg-t3975683).

Apologies if this is not the proper repository to report this in - let me know which repo is best for this discussion and I'll close and re-open if necessary.

**Comment by nworb-cire** [comment] 2020-05-05 14:37
This issue is a duplicate of #62 (which should have been the first search result for "fajita") and should be closed to keep all the discussion there.

**Closed** 2020-05-05 14:50 UTC
