### ISSUE TITLE
Line App Notification not working

### ISSUE THREAD

**Issue by dequegorg** [lineageos4microg/docker-lineage-cicd#186] opened 2021-06-17 05:46 UTC
I have LineageOS for microG (lineage_sargo-userdebug 11 RQ2A.210405.005 eng.root.20210411.235807 dev-keys) installed on Pixel3a, together with Line App.

I wax expecting microG would fix the failing notifications in LineageOS, but it didn't. It seems Line app isn't subscribed to microG cloud notification. And according to the support flowchart this issue brings me here.

Expected behaviour: new incoming messages should push notification in background, while app is closed.

Problem: app is not sending notifications until opened.

Attempts at fixing: disabled battery oprimization for app, enabled background data usage, allowed all essential tracking on Tracker Control.
 
I'd like to troubleshoot and possibly fix the notification issue (I work a lot with this app). Thanks.

**Comment by bananer** [comment] 2021-06-17 11:13
In the microG settings app, is Cloud Messaging enabled? Do you see Line App registered there?

**Comment by dequegorg** [comment] 2021-06-17 12:06
> In the microG settings app, is Cloud Messaging enabled? Do you see Line App registered there?

Cloud Messaging enabled. Line App not registered there.

**Comment by bananer** [comment] 2021-06-17 18:56
If cloud messaging works for other apps, this does not seem like an issue with microG or l4m. Is it a fresh install of Line App or did you restore from a backup? Could you try re-installing?

**Comment by dequegorg** [comment] 2021-06-18 05:16
Hi, I literally just installed LineageOS w/ MicroG yesterday and installed Line App on top. It's all fresh install. 

Note: no application at all is listed under the Cloud Messaging settings of MicroG.

**Comment by Iey4iej3** [comment] 2021-06-18 15:55
First, you need to check that `Google device registration` is on, and `Cloud Messaging` sets `Receive push notifications`. With these enabled, you can try

https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester&hl=en&gl=US

which is an open-source FCM tester, to see where the problem situates.

**Comment by dequegorg** [comment] 2021-06-19 03:49
>check that `Google device registration` is on, 
Check!
>`Cloud Messaging` sets `Receive push notifications`.
Check!
>Push Notification Tester
Prerequisites not met:
- play services installed: check!
- internet connectivity: check!
- register for push notification: **problem!**
- Connection to Server: check!

**Comment by Iey4iej3** [comment] 2021-06-21 09:24
There are problems in the registration. Maybe you could read the logcat, and upload it if you like (be careful: you have to suppress the confidential data in the logcat - note that once uploaded on `GitHub`, you have no way to delete it...)

**Comment by dequegorg** [comment] 2021-06-21 11:15
Hi, thanks. I collected the log. Thanks for the heads-up on data security. I trimmed what I thought seemed irrelevant. I hope I didn't remove anything useful: 

https://pastebin.com/uZEMwqwE

**Comment by bananer** [comment] 2021-06-21 12:09
I searched for "GmsGcmRegister: java.lang.RuntimeException: Checkin disabled" which led me to https://github.com/microg/GmsCore/issues/1329

There are a few possible workarounds mentioned in that issue.

Seems like this is an issue with microG and not caused by lineageos4microg, so I will close this.

**Closed by bananer** 2021-06-21 12:09 UTC
