### ISSUE TITLE
Kebab Build Failing + Workaround

### ISSUE THREAD

**Issue by shadowdognh** [lineageos4microg/docker-lineage-cicd#220] opened 2021-09-03 11:10 UTC
Full disclosure- this is my first time using docker and first time I've built android from source in many years. 

The computer running the build is running a fresh install of Ubuntu 21.04 with docker installed via the instructions here: https://docs.docker.com/engine/install/ubuntu/

This is the command line I used

```
sudo docker run \
    -e "BRANCH_NAME=lineage-18.1" \
    -e "DEVICE_LIST_LINEAGE_18_1=kebab" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -e "OTA_URL=https://rover.degradedfun.local/api" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    -v "/home/user/keys:/srv/keys" \
    -v "/home/user/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```

If I run the build _without_ including the manifest xml for the extras (https://github.com/lineageos4microg/android_prebuilts_prebuiltapks) the build succeeds, the resulting file is flashable and runs fine albeit without any of the microg bits. If I add the XML to the manifests directory the build gets all the way to the end and fails with this error:

```
Running delta_generator with args: --out_file=/srv/src/LINEAGE_18_1/out/soong/.temp/payload-0xF8QS.bin --partition_names=boot:dtbo:odm:product:recovery:system:system_ext:vbmeta:vbmeta_system:vendor --new_partitions=/srv/src/LINEAGE_18_1/out/soong/.temp/boot.img.hcMJOM:/srv/src/LINEAGE_18_1/out/soong/.temp/dtbo.img.oxwgkg:/srv/src/LINEAGE_18_1/out/soong/.temp/odm.img.TcyP32:/srv/src/LINEAGE_18_1/out/soong/.temp/product.img.fQQ8y5:/srv/src/LINEAGE_18_1/out/soong/.temp/recovery.img.plJRKB:/srv/src/LINEAGE_18_1/out/soong/.temp/system.img.bWDNz7:/srv/src/LINEAGE_18_1/out/soong/.temp/system_ext.img.d2ETpD:/srv/src/LINEAGE_18_1/out/soong/.temp/vbmeta.img.QuMauy:/srv/src/LINEAGE_18_1/out/soong/.temp/vbmeta_system.img.OQDPBq:/srv/src/LINEAGE_18_1/out/soong/.temp/vendor.img.yno8ZU --new_mapfiles=::/srv/src/LINEAGE_18_1/out/soong/.temp/odm.map.8qmWFI:/srv/src/LINEAGE_18_1/out/soong/.temp/product.map.WpZxXd::/srv/src/LINEAGE_18_1/out/soong/.temp/system.map.ZRf3nL:/srv/src/LINEAGE_18_1/out/soong/.temp/system_ext.map.5OicOH:::/srv/src/LINEAGE_18_1/out/soong/.temp/vendor.map.8Gxdlh --major_version=2 --max_timestamp=1630414248 --new_postinstall_config_file=/srv/src/LINEAGE_18_1/out/soong/.temp/postinstall_config.NlasL8 --dynamic_partition_info_file=/srv/src/LINEAGE_18_1/out/soong/.temp/dynamic_partitions_info.jMkpKo
[0831/145706.804925:ERROR:payload_generation_config.cc(200)] Sum of sizes in oneplus_dynamic_partitions_partition_list is 3783843840, which is greater than oneplus_dynamic_partitions_size (3753902080)
[0831/145706.805029:FATAL:generate_delta_main.cc(619)] Check failed: payload_config.target.ValidateDynamicPartitionMetadata(). 
```
It seems like including the extra packages for MicroG puts the ROM over a file size limit of some sort? 

I found that I could get the build to succeed with MicroG included by including the XML file in the manifests directory & adding '-e "WITH_GMS=true" \' to the docker command line. The resulting bootloader and ROM are both flashable and seem to work fine. I am not sure if there are any disadvantages to including that option.

**Comment by KenVanHoeylandt** [comment] 2021-09-03 11:18
This is a duplicate of https://github.com/lineageos4microg/docker-lineage-cicd/issues/213
Main ongoing issue is https://github.com/lineageos4microg/docker-lineage-cicd/issues/185

> It seems like including the extra packages for MicroG puts the ROM over a file size limit of some sort?

Yes.

**Comment by petefoth** [comment] 2023-07-27 10:30
This appears to be fixed now

Closing

**Closed by petefoth** 2023-07-27 10:30 UTC
