### ISSUE TITLE
FP5 vendor_boot image version missmatch

### ISSUE THREAD

**Issue by Maddin-619** [lineageos4microg/docker-lineage-cicd#673] opened 2024-08-25 21:42 UTC
Not sure if it's the right place to report this issue. But I discoverd some problems with the FP5 builds:
When I launch netflix it crashes with an error that it could not found a DRM HAL implementation. Since the DRM impl is provided by the vendor partition I unpacked it and found out, that the vendor image is based on Android 13. The upstream linageos builds already provide vendor blobs targetting Android 14, which I assume are extracted from the new released offical [FP5 OS](https://support.fairphone.com/hc/en-us/articles/18682800465169-Fairphone-5-OS-Release-Notes). So I thing the vendor image included in the linage4microg builds is out dated and can be the root for the DRM Problems.

**Comment by petefoth** [comment] 2024-08-26 04:54
We build using the same git repos as upstream LOS. For the FP5 vendor blobs, we use https://github.com/TheMuppets/proprietary_vendor_fairphone_FP5. 

There have been [three commits to that repo](https://github.com/TheMuppets/proprietary_vendor_fairphone_FP5/commits/lineage-21/) since our latest build for FP5 on 15th August, including [FP5: Bump to FP5.UT20.B.041.20240624](https://github.com/TheMuppets/proprietary_vendor_fairphone_FP5/commit/7c539b39ab764c3ba9139b3cde8921e27f5d5c08) which - from the commit message - looks like it may address this issue. We will pick that commit up in out next build run, so it will be interesting to see if the Netflix crash is fixed in that build.

Thanks for looking into this

**Comment by Maddin-619** [comment] 2024-09-15 22:49
With the latest update lineage-21.0-20240914-microG the issue is still present. I can confirm that the vendor image now targents Android 14. But when I open netflix I get following error:
```
1726440304.418 10317 29358 29424 E DrmHalAidl: uuid=[edef8ba979d64ace a3c827dcd51d21ed] Failed to make drm plugin: 6
1726440304.418 10317 29358 29424 E DrmHalHidl: uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
```

**Comment by petefoth** [comment] 2024-09-16 05:44
I would be surprised if the problem with Netflix is caused by problems withe the `vendor_boot.img`. I have created a new issue #684 to track this problem, and I will close this issue, since our build now has the correct vendor blobs

**Closed by petefoth** 2024-09-16 05:44 UTC
