### ISSUE TITLE
Oneplus 6 latest build broken

### ISSUE THREAD

**Issue by IGNNE** [lineageos4microg/docker-lineage-cicd#651] opened 2024-07-07 09:02 UTC
Oneplus 6 / enchilada, clean LOS Microg 21 install. 

Installed the July update, neither wifi nor mobile radio worked. Tiles either greyed out or not doing anything.

I cannot get you any logs, since I've sadly tried to install the June version over it, which (without warning) wiped my flash drive :(

**Comment by petefoth** [comment] 2024-07-07 09:30
Sorry about that - no idea what is causing it.

I have moved the latest build to https://download.lineage.microg.org/enchilada/not_working/

Have you tried installing the latest official LineageOS build (from https://download.lineageos.org/devices/enchilada/builds) to see whether the problem is specific to los4microG?

**Comment by IGNNE** [comment] 2024-07-07 10:04
Weirdly enough, on the latest Lineage nightly, wifi and mobile radio work just fine.

**Comment by petefoth** [comment] 2024-07-07 10:13
Strange! I guess we'll have to wait for next month's build and see how that goes. Or if I have time when the build run is done I could try another build them.

**Comment by jberggg** [comment] 2024-07-08 06:11
Same issue with the fajita build (Oneplus 6T). I haven't downgraded yet so I could get you some logs. Where can I find it?

**Comment by petefoth** [comment] 2024-07-08 06:18
> Same issue with the fajita build (Oneplus 6T). I haven't downgraded yet so I could get you some logs. Where can I find it?

Thanks: This page describes how to go about getting logs https://forum.xda-developers.com/t/guide-providing-a-good-logcat.3814517/

I'll take down the `fajita` build now

**Comment by jberggg** [comment] 2024-07-08 06:25
Perfect. And you would need a boot log? 

What is the recommended downgrade strategy without loosing data, downgrade by adb to previous version?

**Comment by petefoth** [comment] 2024-07-08 07:50
> And you would need a boot log?

I don't think a boot log will help (I\m not even sure that I will be able to get much from a logcat, but I'm prepared to try

> What is the recommended downgrade strategy without loosing data, downgrade by adb to previous version or copying the release to the phone and using the lineageos updater app?

I don't know of any way to downgrade without formatting / factory resetting and losing your data. I suggest the following:
1. Use either (or both) of the following to backup your user-installed apps and (some) data
    1. https://github.com/AndDiSa/android_backup_project/ - requires rooted debugging and a LInux machine, real or virtual. Will backup and restore all of your apps, and some data: See [this post](https://community.e.foundation/t/how-to-do-a-nandroid-backup-without-twrp/47519/8) for guidance on how to use the tool and [here](https://code.binbash.rocks:8443/mAid/issue_tracker/issues/101#issuecomment-654) for some info on what will and will not get restored
    2. https://github.com/mrrfv/open-android-backup will only backup apps, not their data, but that's the biggest hassle when setting up after a format. 
2. Use any in-app backup / export / sync  functionality provided by the apps you use. e.g.
    1.  K-9 has 'export settings, 
    2. QKSMS has in-app backup functionality, or you can use SMS Import Export from F-droid for messages, call logs & contacts
    3. Lawnchair launcher has in-app 
    4. DAVx5 / ICSx5 /NextCloud NOtes & Sync Client allow synching COntacts, Calendar, Notes, Tasks, and files / documents / photos

Then flash the old ROM using `adb sideload` without formatting your data partition: if you are lucky, the older version ***may*** work, but probably you will have to format, reboot and complete first time setup, then restore whatever you need from the backups, exports & syncs you made.

Good luck!

**Comment by jberggg** [comment] 2024-07-08 07:56
> I don't think a boot log will help (I'm not even sure that I will be able to get much from a logcat, but I'm prepared to try)

Ah ok, so just a full dump or however you call it. Where would I provide you that log. Here? Not sure if there is sensitive information in it...

> I don't know of any way to downgrade without formatting / factory resetting and losing your data. I suggest the following

Hmm I think I remember that I successfully downgraded in the past. But of course there is a risk of loosing data. I have app backups through the lineageos built-in backup-mechanism.

I think I can live without data connection for a day but not for days. Would it be an option to re-run the cicd to perform new builds as the latest nightly seems to fix it?

**Comment by petefoth** [comment] 2024-07-08 08:07
> Ah ok, so just a full dump or however you call it. Where would I provide you that log. Here? Not sure if there is sensitive information in it..

Upload it to this 'file drop' directory on my NextCloud account: https://murena.io/s/YGsdPQ5pRwmHosf I promise to delete it after I've tried to work out what's going on.

> I think I can live without data connection for a day but not for days. Would it be an option to re-run the cicd to perform new builds as the latest nightly seems to fix it?

At the moment, there is a build run in progress which is going to take another couple of weeks to complete (building for around 250 devices in all). I don't think it is possible to run another build alongside without risking both build failing. I'll have a think, and see if I can find a way, but I'm not promising

**Comment by petefoth** [comment] 2024-07-08 08:41
OK, I've started a build for both devices on a new cloud server. When It's done I'll let you kniw where to download from. The builds will be sined with my personal keys, not the los4microg keys, and you will have to install manually, ignoring the signature verification error. Also, the build won't pick up the next official OTA update: when that arrives (I'll report here) you'll need to download that, and install it manually

**Comment by petefoth** [comment] 2024-07-08 08:47
> Do the same data-loss risks apply when manual updating to the new "custom" build and later on back to the official build or is this more a problem when downgrading to an older version?

No. Manually installing a newer version is usually just the same as installing a newer version via the Updater app. So you should be able to install it over your current build. Problems are with trying to install an older version

**Comment by petefoth** [comment] 2024-07-08 08:49
Also, see this issue on the official LOS Reddit: https://old.reddit.com/r/LineageOS/comments/1dxer97/please_help_oneplus_6t_fajita/

**Comment by jberggg** [comment] 2024-07-08 13:15
That would be awesome. Thank you! 

I will upload the logs if this build doesn't fix the issue.

**Comment by petefoth** [comment] 2024-07-08 21:40
- New `enchilada` build at https://murena.io/s/76QofZkJ8ewtcfP
- New `fajita` build at https://murena.io/s/oeMW6iJaT6c5K2S

Please note what I wrote earlier
> The builds will be signed with my personal keys, not the los4microg keys, and you will have to install manually, ignoring the signature verification error. Also, the build won't pick up the next official OTA update: when that arrives (I'll report here) you'll need to download that, and install it manually

**Comment by petefoth** [comment] 2024-07-08 21:59
Looks like this is a problem with upstream, official LineageOS too: see https://gitlab.com/LineageOS/issues/android/-/issues/7380.

So it may be the new builds wont work ether 😢

**Comment by jberggg** [comment] 2024-07-09 05:19
hmmm @IGNNE said that the latest Nightly fixed the issue. But maybe this is only true for enchilada...

I will give it a go and report back. Thank you for the build!

**Comment by petefoth** [comment] 2024-07-09 05:30
See also this issue about a WiFi issue with `enchilada`: https://gitlab.com/LineageOS/issues/android/-/issues/7381

**Comment by jberggg** [comment] 2024-07-09 06:18
Your build fixes my fajita 🥳 Thank you very much Pete!

**Comment by IGNNE** [comment] 2024-07-14 21:00
That is indeed weird, my enchilada has been running on `21-20240704-NIGHTLY-enchilada` since this issue started, and everything works. I haven't done any further experiments or upgrades, because I have been travelling, but I hope I have some more time this week.

Thanks to you all for looking into this! Very much appreciated!

**Comment by petefoth** [comment] 2024-07-24 18:08
> * New `enchilada` build at https://murena.io/s/76QofZkJ8ewtcfP
> 
>     * New `fajita` build at https://murena.io/s/oeMW6iJaT6c5K2S
> 
> 
> Please note what I wrote earlier
> 
> > The builds will be signed with my personal keys, not the los4microg keys, and you will have to install manually, ignoring the signature verification error. Also, the build won't pick up the next official OTA update: when that arrives (I'll report here) you'll need to download that, and install it manually

New official builds are now available at
- https://download.lineage.microg.org/enchilada/
- https://download.lineage.microg.org/fajita/

These ***will receive*** OTA updates in future, but if you are using one of the emergency builds linked above, you will need to install the new official builds manually. I have deleted the emergency builds.
 
@IGNNE @jberggg : Please report back whether your issues are fixed

@IGNNE Please feel free to close the issue if the new build works for both of you

**Comment by IGNNE** [comment] 2024-07-26 16:42
Will do as soon as I come home on the weekend!

**Comment by Forage** [comment] 2024-07-29 16:23
Don't let the lack of response be a measurement of interest. I'd be happy to test but I just can't afford to be unreachable at the moment. So I'm just not taking the risk yet.

Your building efforts are highly appreciated. Many thanks for allowing me to keep my phone updated.

**Comment by jberggg** [comment] 2024-07-29 18:51
@petefoth I just installed the most recent Fajita build and Wifi and cellular connectivity works 💪🏽 

Thank you again for your help and also the notice about the new builds. Much appreciated!

**Comment by Theta-Dev** [comment] 2024-07-30 00:50
I have just installed it on my OnePlus 6 (enchilada) and it works as well.

**Comment by Forage** [comment] 2024-07-30 06:40
Thanks for the confirmation @Theta-Dev, it's working for me as well.

**Comment by st3rox** [comment] 2024-07-31 06:04
Installed July 24th enchilada update, no issues
Thanks for the extra build run @petefoth

**Comment by petefoth** [comment] 2024-07-31 06:33
Looks like things are working normally now on both devices.

I'll close this now, and I'll be interested to see what happens with the scheduled August build, which will probably arribe in the next week or so

**Closed** 2024-07-31 06:33 UTC
