### ISSUE TITLE
17.1 for cheeseburger

### ISSUE THREAD

**Issue by leo-lb** [lineageos4microg/docker-lineage-cicd#126] opened 2020-11-20 11:40 UTC
Lineage OS upstream has 17.1 since a little while: https://download.lineageos.org/cheeseburger

However, Lineage OS for MicroG does not: https://download.lineage.microg.org/cheeseburger/

What can I do to help and make it happen?

Thank you

**Comment by ArchangeGabriel** [comment] 2020-11-20 14:06
Duplicate of https://github.com/lineageos4microg/l4m_website/issues/61.

Device get updated when some maintainer has the time to review and enable them.

**Comment by leo-lb** [comment] 2020-11-20 19:29
@ArchangeGabriel Thank you, how can we become that maintainer? :-) I have good enough skills in pretty much every topic from development to sysadmin to handle such things.

**Comment by leo-lb** [comment] 2020-12-03 21:51
It is now available! Closing

**Closed** 2020-12-03 21:52 UTC
