### ISSUE TITLE
Withdraw & Rebuild builds affected from broken sound

### ISSUE THREAD

**Issue by SpaceAgeHero** [lineageos4microg/docker-lineage-cicd#135] opened 2021-01-11 08:50 UTC
Hi,

sound is broken on my Mi Mix 2S. Issue has already been reported by many users on XDA:
https://forum.xda-developers.com/t/rom-official-lineageos-17-1-weeklies-for-xiaomi-mi-mix-2s.3974661/page-27

Unfortunately I can't get the available previous builds to boot at all. Tried different Vendor + FW combinations as well.
Can someone please help me out or provide me the October 2020 build for polaris? (Don't have it anymore)

Perhaps an emergency build can be pushed too, once this was fixed in the main LineageOS branch.

**Comment by ethernetpl** [comment] 2021-01-11 09:18
I have the same probleim with this build. Downgrade to December build ends up with boot-loop. On Xda the people say that they succesfully downgrade to 01.01.2020r. 

Is there a possibility to provide 01.01.2020r. build for users to fix their devices?

P.S Lineage OS removed 08.01.2020r. build from the site.

**Comment by kurt-by** [comment] 2021-01-11 19:39
@spolack I think, you should urgently remove the download

**Comment by spolack** [comment] 2021-01-11 20:20
Removal done. Thank you.

 Hopefully they'll fix it.. As i wont work actively on this, close.

**Comment by esldniw** [comment] 2021-01-11 20:28
Same issue with Mi 8 (dipper). Unable to downgrade.

Seems this applies to all LineageOS builds from 08.01.2021: https://www.reddit.com/r/LineageOS/comments/ku675d/warning_broken_20210108_update_audio_problems/?ref_source=embed&ref=share

**Comment by kurt-by** [comment] 2021-01-11 20:33
17.1-20210107-microG-a3xelte has no problems

**Comment by ethernetpl** [comment] 2021-01-11 20:39
Now, the current solution is to downgrade to 01.01.2020r., this build is available for polaris on Lineageos site (https://download.lineageos.org/polaris), but not for microg.

@spolack Could you provide 01.01.2020r. build? We don't know when Lineage OS will provide a fix. As reported on XDA users succesffuly downgrade to this version, the sound is back. For me downgrade to the december microg build end up with a bootloop

**Comment by spolack** [comment] 2021-01-11 20:56
For now withdrawn:
* polaris
* dipper
* xz2c

Please report if you face similar issues with other devices.

**Comment by SpaceAgeHero** [comment] 2021-01-12 09:48
Second the request by @ethernetpl as I'm stuck with a heavily restricted device. Can't even make a phone call.

**Comment by spolack** [comment] 2021-01-12 09:53
I'm sorry. not possible i think.

**Comment by esldniw** [comment] 2021-01-12 12:58
I also support the request for a solution of some kind (e.g. Jan 1st build, or the next LineageOS weekly build).

**Comment by efouladi** [comment] 2021-01-12 22:18
Same issue here with z3c. LineageOS already put an update out on 2012-01-12. Could you please provide a build based on that? I tried downgrading by flashing the previous version (2020-12-07) of lineagos-microg for the device but it didn't work. It boots but it just crashes the UI after trying to unlock and pops back to the lock screen

**Comment by spolack** [comment] 2021-01-13 10:18
z3c build has been removed. Can you confirm that those devices have working builds now? I'll then spin up another build for the affected devices

**Comment by efouladi** [comment] 2021-01-13 11:14
I can't really confirm myself but according to this post: https://forum.xda-developers.com/t/official-lineageos-17-1-for-z3c.4160347/page-7#post-84277503 it should be fixed by now. Is it possible for you to give me an artifact based on the latest build? That way I can test and report back

**Comment by ethernetpl** [comment] 2021-01-13 21:56
What is the planned solution for broken devices? As 01.01.2021 build is the newest on Lineage OS shouldn't be enough to rerun the build on CD? Do you build every artefact manually?

If it not possible, Will you publish the next weekly build? Or we will have to wait for the next month build?
The best if we will know what to expect as for know I don't know if should get a temporary phone, or the fix will be quickly published.

**Comment by spolack** [comment] 2021-01-14 14:00
gingko also seems to be affected according to #137

**Comment by spolack** [comment] 2021-01-14 14:04
Rebuild is triggered for dipper, gingko, polaris, z3c.

**Comment by ethernetpl** [comment] 2021-01-14 19:00
@spolack Thanks for the rebuild, the phone now works flawless, sound is back

**Comment by esldniw** [comment] 2021-01-14 20:03
Super, thanks a lot! Dipper is also fully working again

**Comment by efouladi** [comment] 2021-01-14 20:32
I can confirm z3c is all fixed too. thanks

**Comment by SpaceAgeHero** [comment] 2021-01-14 20:54
Polaris confirmed. Thank you!

**Closed** 2021-01-14 21:06 UTC
