### ISSUE TITLE
Feature request: disable green pop-up location marker for UnifiedNLP backends

### ISSUE THREAD

**Issue by LuccoJ** [lineageos4microg/docker-lineage-cicd#396] opened 2023-02-12 20:11 UTC
The not-so-new-anymore green status bar indication for location use shows up extremely often on a microG phone. That way it is both distracting (it is kind of _meant_ to be intrusive so the user is clearly aware), and mostly loses its usefulness as most of the time it shows up, no application is actually requesting a location from the user's point of view, even though that's technically happening due to how UnifiedNLP and Android location work.

I propose to make all UnifiedNLP modules exempt from the indicator with either of the following policies, whichever is easier:

* preferably, figure out which UnifiedNLP backends are enabled in microG, and make those exempt;
* exempt all known UnifiedNLP backends by package name and signature.

I don't think exempting only the ones included with LineageOS for microG would be sufficient, as there are several others that can be genuinely useful, and it is intended to be an open system.

Here is a list of ones I know about:

* org.microg.nlp.backend.apple
* org.fitchfamily.android.dejavu
* org.fitchfamily.android.gsmlocation
* org.gfd.gsmlocation
* helium314.localbackend
* info.spotcomms.wlanbackend
* org.microg.nlp.backend.ichnaea
* org.openbmap.unifiedNlp
* org.fitchfamily.android.wifi_backend

I believe these are all available from F-Droid.

I would also consider making what I propose opt-out, as some people may still feel their location is sensitive enough that they will want to know even about UnifiedNLP backends accessing it (or proxies to it).

[This Reddit post](https://np.reddit.com/r/LineageOS/comments/vico0b/disable_location_notification_forever/ideyqhp/) appears to hint to a way to whitelist an app from causing the marker to show, presumably referencing [this patch](https://review.lineageos.org/c/LineageOS/android_vendor_lineage/+/332077).

**Comment by chirayudesai** [comment] 2023-02-13 09:11
https://review.calyxos.org/q/topic:location-indicators

**Comment by petefoth** [comment] 2023-07-25 11:27
I'm pretty sure we take the backends from upstream https://github.com/microg/UnifiedNlp

In the changes linked in the previous comment, disabling the location marker involves forking or patching the file `core/java/android/permission/PermissionManager.java`

This project doesn't have the time or resources ( or motivation :) ) to create and maintain a patch or a fork, for what is a relative minor UI change, and one which not all our users may want.

Closing this issue

**Comment by LuccoJ** [comment] 2023-07-25 15:00
Apparently this project is not even aware that since I posted this feature request, UnifiedNLP has been abandoned upstream... so whatever.

**Comment by LuccoJ** [comment] 2023-07-26 01:08
FWIW, it's not just a UI issue because on phones that slow the screen refresh down to 60Hz from 90Hz or 120Hz to save power, the green indicator lighting up causes the screen refresh rate to jump up again, and since in my experience this happens pretty much continuously (maybe I just have very many NLP modules active and it's fine for other people), it means the screen is almost never dozing off.

**Comment by dicer** [comment] 2023-07-26 11:27
I think this request is still valid. The "location used" popup/notification still pops up all the time and is quite annoying.

Here is my thinking:
- this project is about integrating microg with lineageos 
- this issue is caused by integrating microg into lineageos
- this issue can not be fixed in either microg, nor lineageos
- although all microg users are affected by this, this project is one of the few locations this can be fixed as we could patch the OS for microg

I think we should at least keep it open so someone can find valid pointers on how to address this.

**Comment by petefoth** [comment] 2023-08-17 19:59
If someone finds a way to fix this, then we can look at to, but we won't be spending any time on it.

It still looks like an upstream issue to me, but...whatever

**Comment by LuccoJ** [comment] 2023-08-17 23:56
The upstream you mean being...? MicroG, LineageOS, AOSP...?

**Comment by petefoth** [comment] 2023-08-18 05:38
> The upstream you mean being...? MicroG, LineageOS, AOSP...?

Yes, probably one of those ;)

Seriously, the problem is not in **our** code, since the only code this project owns and maintains are the signature spoofing patches. Fixing this would probably involve changes in one or more of our upstream projects. Since we don;t plan to 'fix'  it, I don't plan tp investigate much further. 

As I said, if someone else wants to investigate it, that's great, and we can look at what they discover

**Comment by rgarisson** [comment] 2023-08-18 11:19
Hi, 
I second that it's a microg issue, on how it handle location backend. I have been using the last microg version from may (v0.2.28) and no more intempestive green light. The green light show only a couple of second when I open a location based app. So this issue seems to already been solved. (I precise that I was really annoyed by this green light too before)

The last microg version is not indicated as "recommended" on fdroid because the new location backend management is still a work in progress but for me it has been working flawlessly since it release. Most apps that didn't work before does now. And location demand are more responsive and accurate. Nearly as with the stock oneplus rom I had before.

**Comment by petefoth** [comment] 2023-08-18 18:30
> Probably can be put to rest.

Thanks! Closing

**Closed by petefoth** 2023-08-18 18:30 UTC
Labels: Upstream issue, Fix sometime
